/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.microlabs.ess.payslip.form;

import java.util.ArrayList;
import java.util.LinkedList;

import org.apache.struts.action.ActionForm;

/** 
 * MyEclipse Struts
 * Creation date: 04-27-2013
 * 
 * XDoclet definition:
 * @struts.form name="attendenceForm"
 */
public class PayslipForm extends ActionForm {
	
	private String mesage;
	private String dat;
	private String empcode;
	private String empcod;
	private String comaddr;
	private String paymnt;
	private String bnkname;
	private String empname;
	private String baccno;
	private String empaddr;
	private String pfno;
	private String esino;
	private String desg;
	private String panno;
	private String dept;
	private String daypayd;
	private String doj;
	private String worgdays;
	private String daywrkd;
	private String lop;
	private String repmng;
	private String el;
	private String sl;
	private String cl;
	private String arrears_totEarn;
	private String current_totEarn;
	private String arrears_totDeduc;
	private String current_totDeduc;
	private String netpay;
	private String location;
	
	private String ea;
	private String eh;
	private String ec;
	private String da;
	private String dh;
	private String dc;
	
	private String payGroup;
	private LinkedList payGroupID;
	private LinkedList payGroupShort_Name;
	
	ArrayList array1 = new ArrayList();
	ArrayList array2 = new ArrayList();
	
	
	private ArrayList ar_id=new ArrayList();
    private ArrayList ar_name=new ArrayList();
    
    private int sTAFF_CAT_CODE ;
    private int sTATE_ID;
    private int lOC_ID;

    private int gRD_ID;
    private int dSG_ID;
    private int dPT_ID;
    private String cUR_KEY;
    private String pAY_MODE;
    private int bANK_ID;
    private String bANK_ACC_TYP;

    private String bANK_ACC_NO;
    private String bANK_BRANCH;
    private String iFSC_CODE;
    private String mICR_CODE;
    private double wKG_DAYS;
    private double wKD_DAYS;
    private double lEV_DAYS;
    private double lOP_DAYS;
    private double tOT_EARN;
    private double tOT_DEDN;
    private double tOT_AEARN;
    private double tOT_ADEDN;

    private double nET_EARN;

    private String cR_DAT;
    private String cPU_TM;
    private String eNT_USER_NAME;
    
    private int sAL_ID;
    private String sAL_TYPE;
    private double sAL_AMT;
    private String iNVE_CO;
    private double aRR_AMT;
    private double iNP_SLIP;
    private String message;
    private String message2;
    
    
    
    
	public String getMessage2() {
		return message2;
	}
	public void setMessage2(String message2) {
		this.message2 = message2;
	}
	public int getsTAFF_CAT_CODE() {
		return sTAFF_CAT_CODE;
	}
	public void setsTAFF_CAT_CODE(int sTAFF_CAT_CODE) {
		this.sTAFF_CAT_CODE = sTAFF_CAT_CODE;
	}
	public int getsTATE_ID() {
		return sTATE_ID;
	}
	public void setsTATE_ID(int sTATE_ID) {
		this.sTATE_ID = sTATE_ID;
	}
	public int getlOC_ID() {
		return lOC_ID;
	}
	public void setlOC_ID(int lOC_ID) {
		this.lOC_ID = lOC_ID;
	}
	public int getgRD_ID() {
		return gRD_ID;
	}
	public void setgRD_ID(int gRD_ID) {
		this.gRD_ID = gRD_ID;
	}
	public int getdSG_ID() {
		return dSG_ID;
	}
	public void setdSG_ID(int dSG_ID) {
		this.dSG_ID = dSG_ID;
	}
	public int getdPT_ID() {
		return dPT_ID;
	}
	public void setdPT_ID(int dPT_ID) {
		this.dPT_ID = dPT_ID;
	}
	public String getcUR_KEY() {
		return cUR_KEY;
	}
	public void setcUR_KEY(String cUR_KEY) {
		this.cUR_KEY = cUR_KEY;
	}
	public String getpAY_MODE() {
		return pAY_MODE;
	}
	public void setpAY_MODE(String pAY_MODE) {
		this.pAY_MODE = pAY_MODE;
	}
	public int getbANK_ID() {
		return bANK_ID;
	}
	public void setbANK_ID(int bANK_ID) {
		this.bANK_ID = bANK_ID;
	}
	public String getbANK_ACC_TYP() {
		return bANK_ACC_TYP;
	}
	public void setbANK_ACC_TYP(String bANK_ACC_TYP) {
		this.bANK_ACC_TYP = bANK_ACC_TYP;
	}
	public String getbANK_ACC_NO() {
		return bANK_ACC_NO;
	}
	public void setbANK_ACC_NO(String bANK_ACC_NO) {
		this.bANK_ACC_NO = bANK_ACC_NO;
	}
	public String getbANK_BRANCH() {
		return bANK_BRANCH;
	}
	public void setbANK_BRANCH(String bANK_BRANCH) {
		this.bANK_BRANCH = bANK_BRANCH;
	}
	public String getiFSC_CODE() {
		return iFSC_CODE;
	}
	public void setiFSC_CODE(String iFSC_CODE) {
		this.iFSC_CODE = iFSC_CODE;
	}
	public String getmICR_CODE() {
		return mICR_CODE;
	}
	public void setmICR_CODE(String mICR_CODE) {
		this.mICR_CODE = mICR_CODE;
	}
	public double getwKG_DAYS() {
		return wKG_DAYS;
	}
	public void setwKG_DAYS(double wKG_DAYS) {
		this.wKG_DAYS = wKG_DAYS;
	}
	public double getwKD_DAYS() {
		return wKD_DAYS;
	}
	public void setwKD_DAYS(double wKD_DAYS) {
		this.wKD_DAYS = wKD_DAYS;
	}
	public double getlEV_DAYS() {
		return lEV_DAYS;
	}
	public void setlEV_DAYS(double lEV_DAYS) {
		this.lEV_DAYS = lEV_DAYS;
	}
	public double getlOP_DAYS() {
		return lOP_DAYS;
	}
	public void setlOP_DAYS(double lOP_DAYS) {
		this.lOP_DAYS = lOP_DAYS;
	}
	public double gettOT_EARN() {
		return tOT_EARN;
	}
	public void settOT_EARN(double tOT_EARN) {
		this.tOT_EARN = tOT_EARN;
	}
	public double gettOT_DEDN() {
		return tOT_DEDN;
	}
	public void settOT_DEDN(double tOT_DEDN) {
		this.tOT_DEDN = tOT_DEDN;
	}
	public double gettOT_AEARN() {
		return tOT_AEARN;
	}
	public void settOT_AEARN(double tOT_AEARN) {
		this.tOT_AEARN = tOT_AEARN;
	}
	public double gettOT_ADEDN() {
		return tOT_ADEDN;
	}
	public void settOT_ADEDN(double tOT_ADEDN) {
		this.tOT_ADEDN = tOT_ADEDN;
	}
	public double getnET_EARN() {
		return nET_EARN;
	}
	public void setnET_EARN(double nET_EARN) {
		this.nET_EARN = nET_EARN;
	}
	public String getcR_DAT() {
		return cR_DAT;
	}
	public void setcR_DAT(String cR_DAT) {
		this.cR_DAT = cR_DAT;
	}
	public String getcPU_TM() {
		return cPU_TM;
	}
	public void setcPU_TM(String cPU_TM) {
		this.cPU_TM = cPU_TM;
	}
	public String geteNT_USER_NAME() {
		return eNT_USER_NAME;
	}
	public void seteNT_USER_NAME(String eNT_USER_NAME) {
		this.eNT_USER_NAME = eNT_USER_NAME;
	}
	public int getsAL_ID() {
		return sAL_ID;
	}
	public void setsAL_ID(int sAL_ID) {
		this.sAL_ID = sAL_ID;
	}
	public String getsAL_TYPE() {
		return sAL_TYPE;
	}
	public void setsAL_TYPE(String sAL_TYPE) {
		this.sAL_TYPE = sAL_TYPE;
	}
	public double getsAL_AMT() {
		return sAL_AMT;
	}
	public void setsAL_AMT(double sAL_AMT) {
		this.sAL_AMT = sAL_AMT;
	}
	public String getiNVE_CO() {
		return iNVE_CO;
	}
	public void setiNVE_CO(String iNVE_CO) {
		this.iNVE_CO = iNVE_CO;
	}
	public double getaRR_AMT() {
		return aRR_AMT;
	}
	public void setaRR_AMT(double aRR_AMT) {
		this.aRR_AMT = aRR_AMT;
	}
	public double getiNP_SLIP() {
		return iNP_SLIP;
	}
	public void setiNP_SLIP(double iNP_SLIP) {
		this.iNP_SLIP = iNP_SLIP;
	}
	public String getMessage() {
		return message;
	}
	public void setMessage(String message) {
		this.message = message;
	}
	public String getINVE_CO() {
		return iNVE_CO;
	}
	public void setINVE_CO(String inve_co) {
		iNVE_CO = inve_co;
	}
	public int getSAL_ID() {
		return sAL_ID;
	}
	public void setSAL_ID(int sal_id) {
		sAL_ID = sal_id;
	}
	public String getSAL_TYPE() {
		return sAL_TYPE;
	}
	public void setSAL_TYPE(String sal_type) {
		sAL_TYPE = sal_type;
	}
	public double getSAL_AMT() {
		return sAL_AMT;
	}
	public void setSAL_AMT(double sal_amt) {
		sAL_AMT = sal_amt;
	}
	public double getARR_AMT() {
		return aRR_AMT;
	}
	public void setARR_AMT(double arr_amt) {
		aRR_AMT = arr_amt;
	}
	public double getINP_SLIP() {
		return iNP_SLIP;
	}
	public void setINP_SLIP(double inp_slip) {
		iNP_SLIP = inp_slip;
	}
	public int getSTAFF_CAT_CODE() {
		return sTAFF_CAT_CODE;
	}
	public void setSTAFF_CAT_CODE(int staff_cat_code) {
		sTAFF_CAT_CODE = staff_cat_code;
	}
	public int getSTATE_ID() {
		return sTATE_ID;
	}
	public void setSTATE_ID(int state_id) {
		sTATE_ID = state_id;
	}
	public int getLOC_ID() {
		return lOC_ID;
	}
	public void setLOC_ID(int loc_id) {
		lOC_ID = loc_id;
	}
	public int getGRD_ID() {
		return gRD_ID;
	}
	public void setGRD_ID(int grd_id) {
		gRD_ID = grd_id;
	}
	public int getDSG_ID() {
		return dSG_ID;
	}
	public void setDSG_ID(int dsg_id) {
		dSG_ID = dsg_id;
	}
	public int getDPT_ID() {
		return dPT_ID;
	}
	public void setDPT_ID(int dpt_id) {
		dPT_ID = dpt_id;
	}
	public String getCUR_KEY() {
		return cUR_KEY;
	}
	public void setCUR_KEY(String cur_key) {
		cUR_KEY = cur_key;
	}
	public String getPAY_MODE() {
		return pAY_MODE;
	}
	public void setPAY_MODE(String pay_mode) {
		pAY_MODE = pay_mode;
	}
	public int getBANK_ID() {
		return bANK_ID;
	}
	public void setBANK_ID(int bank_id) {
		bANK_ID = bank_id;
	}
	public String getBANK_ACC_TYP() {
		return bANK_ACC_TYP;
	}
	public void setBANK_ACC_TYP(String bank_acc_typ) {
		bANK_ACC_TYP = bank_acc_typ;
	}
	public String getBANK_ACC_NO() {
		return bANK_ACC_NO;
	}
	public void setBANK_ACC_NO(String bank_acc_no) {
		bANK_ACC_NO = bank_acc_no;
	}
	public String getBANK_BRANCH() {
		return bANK_BRANCH;
	}
	public void setBANK_BRANCH(String bank_branch) {
		bANK_BRANCH = bank_branch;
	}
	public String getIFSC_CODE() {
		return iFSC_CODE;
	}
	public void setIFSC_CODE(String ifsc_code) {
		iFSC_CODE = ifsc_code;
	}
	public String getMICR_CODE() {
		return mICR_CODE;
	}
	public void setMICR_CODE(String micr_code) {
		mICR_CODE = micr_code;
	}
	public double getWKG_DAYS() {
		return wKG_DAYS;
	}
	public void setWKG_DAYS(double wkg_days) {
		wKG_DAYS = wkg_days;
	}
	public double getWKD_DAYS() {
		return wKD_DAYS;
	}
	public void setWKD_DAYS(double wkd_days) {
		wKD_DAYS = wkd_days;
	}
	public double getLEV_DAYS() {
		return lEV_DAYS;
	}
	public void setLEV_DAYS(double lev_days) {
		lEV_DAYS = lev_days;
	}
	public double getLOP_DAYS() {
		return lOP_DAYS;
	}
	public void setLOP_DAYS(double lop_days) {
		lOP_DAYS = lop_days;
	}
	public double getTOT_EARN() {
		return tOT_EARN;
	}
	public void setTOT_EARN(double tot_earn) {
		tOT_EARN = tot_earn;
	}
	public double getTOT_DEDN() {
		return tOT_DEDN;
	}
	public void setTOT_DEDN(double tot_dedn) {
		tOT_DEDN = tot_dedn;
	}
	public double getTOT_AEARN() {
		return tOT_AEARN;
	}
	public void setTOT_AEARN(double tot_aearn) {
		tOT_AEARN = tot_aearn;
	}
	public double getTOT_ADEDN() {
		return tOT_ADEDN;
	}
	public void setTOT_ADEDN(double tot_adedn) {
		tOT_ADEDN = tot_adedn;
	}
	public double getNET_EARN() {
		return nET_EARN;
	}
	public void setNET_EARN(double net_earn) {
		nET_EARN = net_earn;
	}
	public String getCR_DAT() {
		return cR_DAT;
	}
	public void setCR_DAT(String cr_dat) {
		cR_DAT = cr_dat;
	}
	public String getCPU_TM() {
		return cPU_TM;
	}
	public void setCPU_TM(String cpu_tm) {
		cPU_TM = cpu_tm;
	}
	public String getENT_USER_NAME() {
		return eNT_USER_NAME;
	}
	public void setENT_USER_NAME(String ent_user_name) {
		eNT_USER_NAME = ent_user_name;
	}
	public String getPayGroup() {
		return payGroup;
	}
	public void setPayGroup(String payGroup) {
		this.payGroup = payGroup;
	}
	public LinkedList getPayGroupID() {
		return payGroupID;
	}
	public void setPayGroupID(LinkedList payGroupID) {
		this.payGroupID = payGroupID;
	}
	public LinkedList getPayGroupShort_Name() {
		return payGroupShort_Name;
	}
	public void setPayGroupShort_Name(LinkedList payGroupShort_Name) {
		this.payGroupShort_Name = payGroupShort_Name;
	}
	public String getLocation() {
		return location;
	}
	public void setLocation(String location) {
		this.location = location;
	}
	public String getMesage() {
		return mesage;
	}
	public void setMesage(String mesage) {
		this.mesage = mesage;
	}
	public String getDat() {
		return dat;
	}
	public void setDat(String dat) {
		this.dat = dat;
	}
	public String getEmpcode() {
		return empcode;
	}
	public void setEmpcode(String empcode) {
		this.empcode = empcode;
	}
	public String getComaddr() {
		return comaddr;
	}
	public void setComaddr(String comaddr) {
		this.comaddr = comaddr;
	}
	public String getPaymnt() {
		return paymnt;
	}
	public void setPaymnt(String paymnt) {
		this.paymnt = paymnt;
	}
	public String getBnkname() {
		return bnkname;
	}
	public void setBnkname(String bnkname) {
		this.bnkname = bnkname;
	}
	public String getEmpname() {
		return empname;
	}
	public void setEmpname(String empname) {
		this.empname = empname;
	}
	public String getBaccno() {
		return baccno;
	}
	public void setBaccno(String baccno) {
		this.baccno = baccno;
	}
	public String getEmpaddr() {
		return empaddr;
	}
	public void setEmpaddr(String empaddr) {
		this.empaddr = empaddr;
	}
	public String getPfno() {
		return pfno;
	}
	public void setPfno(String pfno) {
		this.pfno = pfno;
	}
	public String getEsino() {
		return esino;
	}
	public void setEsino(String esino) {
		this.esino = esino;
	}
	public String getDesg() {
		return desg;
	}
	public void setDesg(String desg) {
		this.desg = desg;
	}
	public String getPanno() {
		return panno;
	}
	public void setPanno(String panno) {
		this.panno = panno;
	}
	public String getDept() {
		return dept;
	}
	public void setDept(String dept) {
		this.dept = dept;
	}
	public String getDaypayd() {
		return daypayd;
	}
	public void setDaypayd(String daypayd) {
		this.daypayd = daypayd;
	}
	public String getDoj() {
		return doj;
	}
	public void setDoj(String doj) {
		this.doj = doj;
	}
	public String getWorgdays() {
		return worgdays;
	}
	public void setWorgdays(String worgdays) {
		this.worgdays = worgdays;
	}
	public String getDaywrkd() {
		return daywrkd;
	}
	public void setDaywrkd(String daywrkd) {
		this.daywrkd = daywrkd;
	}
	public String getLop() {
		return lop;
	}
	public void setLop(String lop) {
		this.lop = lop;
	}
	public String getRepmng() {
		return repmng;
	}
	public void setRepmng(String repmng) {
		this.repmng = repmng;
	}
	public String getEl() {
		return el;
	}
	public void setEl(String el) {
		this.el = el;
	}
	public String getSl() {
		return sl;
	}
	public void setSl(String sl) {
		this.sl = sl;
	}
	public String getCl() {
		return cl;
	}
	public void setCl(String cl) {
		this.cl = cl;
	}
	public String getArrears_totEarn() {
		return arrears_totEarn;
	}
	public void setArrears_totEarn(String arrears_totEarn) {
		this.arrears_totEarn = arrears_totEarn;
	}
	public String getCurrent_totEarn() {
		return current_totEarn;
	}
	public void setCurrent_totEarn(String current_totEarn) {
		this.current_totEarn = current_totEarn;
	}
	public String getArrears_totDeduc() {
		return arrears_totDeduc;
	}
	public void setArrears_totDeduc(String arrears_totDeduc) {
		this.arrears_totDeduc = arrears_totDeduc;
	}
	public String getCurrent_totDeduc() {
		return current_totDeduc;
	}
	public void setCurrent_totDeduc(String current_totDeduc) {
		this.current_totDeduc = current_totDeduc;
	}
	public String getNetpay() {
		return netpay;
	}
	public void setNetpay(String netpay) {
		this.netpay = netpay;
	}
	public String getEa() {
		return ea;
	}
	public void setEa(String ea) {
		this.ea = ea;
	}
	public String getEh() {
		return eh;
	}
	public void setEh(String eh) {
		this.eh = eh;
	}
	public String getEc() {
		return ec;
	}
	public void setEc(String ec) {
		this.ec = ec;
	}
	public String getDa() {
		return da;
	}
	public void setDa(String da) {
		this.da = da;
	}
	public String getDh() {
		return dh;
	}
	public void setDh(String dh) {
		this.dh = dh;
	}
	public String getDc() {
		return dc;
	}
	public void setDc(String dc) {
		this.dc = dc;
	}
	public ArrayList getArray1() {
		return array1;
	}
	public void setArray1(ArrayList array1) {
		this.array1 = array1;
	}
	public ArrayList getArray2() {
		return array2;
	}
	public void setArray2(ArrayList array2) {
		this.array2 = array2;
	}
	public ArrayList getAr_id() {
		return ar_id;
	}
	public void setAr_id(ArrayList ar_id) {
		this.ar_id = ar_id;
	}
	public ArrayList getAr_name() {
		return ar_name;
	}
	public void setAr_name(ArrayList ar_name) {
		this.ar_name = ar_name;
	}
	public String getEmpcod() {
		return empcod;
	}
	public void setEmpcod(String empcod) {
		this.empcod = empcod;
	}

	
	
	
	
}