/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.attendence.action;

import java.io.File;
import java.io.FileOutputStream;
import java.util.Properties;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import com.attendence.db.attendenceDB;
import com.attendence.form.AttendenceForm;
import com.microlabs.ess.dao.EssDao;
import com.sap.conn.jco.JCoDestination;
import com.sap.conn.jco.JCoDestinationManager;
import com.sap.conn.jco.ext.DestinationDataProvider;
import com.sap.conn.jco.JCoException;
import com.sap.conn.jco.JCoFunction;
import com.sap.conn.jco.JCoTable;
/** 
 * MyEclipse Struts
 * Creation date: 04-27-2013
 * 
 * XDoclet definition:
 * @struts.action path="/attendence" name="attendenceForm" input="/form/attendence.jsp" parameter="method" scope="request" validate="true"
 */
public class AttendenceAction extends DispatchAction {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	
	EssDao ad=EssDao.dBConnection();
	private static final String DESTINATION = "SAP_DESTINATION";
	private void connectSAP() {
		try {
		
			Properties connectProperties = new Properties();// TODO change the
													// details
			connectProperties.setProperty(DestinationDataProvider.JCO_ASHOST,
					"192.168.1.2");
			connectProperties.setProperty(DestinationDataProvider.JCO_SYSNR, "00");
			connectProperties
					.setProperty(DestinationDataProvider.JCO_CLIENT, "900");
			connectProperties.setProperty(DestinationDataProvider.JCO_USER,
					"91524");
			connectProperties.setProperty(DestinationDataProvider.JCO_PASSWD,
					"Micro@1");
			connectProperties.setProperty(DestinationDataProvider.JCO_LANG, "EN");
			File destCfg = new File(DESTINATION + ".jcoDestination");
			
				FileOutputStream fos = new FileOutputStream(destCfg, false);
				connectProperties.store(fos, "SAP_DESTINATION config");
				fos.close();
		} catch (Exception e) {
			throw new RuntimeException("Unable to create the destination file",e);
		}
	}
	
	public ActionForward submit(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		AttendenceForm attendenceForm = (AttendenceForm) form;// TODO Auto-generated method stub
		
		attendenceDB att=new attendenceDB();
		
		int i=0;
		
		i=att.submitdb(attendenceForm.getEmpcode(),attendenceForm.getDat(),request,attendenceForm);
		
		if(i>0)
		{
			request.setAttribute("detailed_att", "detailed_att");
			att.displaydb(attendenceForm.getEmpcode(),request,attendenceForm);
			
		}
		
		else
		{
			attendenceForm.setMesage("Employee Records not found");
		}
		return monthyear(mapping, form, request, response);
	}
	
	
	
	public ActionForward monthyear(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		AttendenceForm attendenceForm = (AttendenceForm) form;// TODO Auto-generated method stub
		
		attendenceDB att=new attendenceDB();
		
		JCoFunction function=null;
		JCoTable a=null;
		
		connectSAP();
		JCoDestination destination;
		try {
			destination = JCoDestinationManager
					.getDestination(DESTINATION);
						// destination
		if (destination == null) {
			
			destination = JCoDestinationManager
					.getDestination(DESTINATION);// TODO change to
														// real
														// destination
			if (destination == null) {
				throw new RuntimeException(
						"Could not connect to SAP, destination not found.");
			}
		}
		
		 function = destination.getRepository().getFunction(
					"ZBAPI_HR_LEAVE");
		if (function == null) {
			throw new RuntimeException(" ZBAPI_HR_LEAVE not found in SAP.");//ZBAPI_HR_PAYSLIP
		}
		} catch (JCoException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}// TODO change to real
								
		
		/* HttpSession session = request.getSession();
		 String employeenumber = (String)session.getAttribute("employeenumber");
		 attendenceForm.setEmpcode(employeenumber);
		att.monthyear(request,attendenceForm);*/
		
		//return submit(mapping, form, request, response);
		
		return mapping.findForward("home");
	}
	
}