/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.attendence.form;

import java.util.ArrayList;

import org.apache.struts.action.ActionForm;

/** 
 * MyEclipse Struts
 * Creation date: 04-27-2013
 * 
 * XDoclet definition:
 * @struts.form name="attendenceForm"
 */
public class AttendenceForm extends ActionForm {
	
	
	private String empcode;
	public String dat;
	private String empcode1;
	private String name;
	private String designation;
	private String department;
	private String doj;
	private String dat1;
	private String mesage;
	private String day;
	private String arr;
	private String arrdesc;
	private String dep;
	private String depdesc;
	private String getday;
	
	ArrayList arrayl = new ArrayList();
	
	private ArrayList ar_id=new ArrayList();
    private ArrayList ar_name=new ArrayList();
	
	
	public String getEmpcode() {
		return empcode;
	}

	public void setEmpcode(String empcode) {
		this.empcode = empcode;
	}

	public String getDat() {
		return dat;
	}

	public void setDat(String dat) {
		this.dat = dat;
	}

	public String getEmpcode1() {
		return empcode1;
	}

	public void setEmpcode1(String empcode1) {
		this.empcode1 = empcode1;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDesignation() {
		return designation;
	}

	public void setDesignation(String designation) {
		this.designation = designation;
	}

	public String getDepartment() {
		return department;
	}

	public void setDepartment(String department) {
		this.department = department;
	}

	public String getDoj() {
		return doj;
	}

	public void setDoj(String doj) {
		this.doj = doj;
	}

	public String getDat1() {
		return dat1;
	}

	public void setDat1(String dat1) {
		this.dat1 = dat1;
	}

	public String getMesage() {
		return mesage;
	}

	public void setMesage(String mesage) {
		this.mesage = mesage;
	}

	public String getDay() {
		return day;
	}

	public void setDay(String day) {
		this.day = day;
	}

	public String getArr() {
		return arr;
	}

	public void setArr(String arr) {
		this.arr = arr;
	}

	public String getArrdesc() {
		return arrdesc;
	}

	public void setArrdesc(String arrdesc) {
		this.arrdesc = arrdesc;
	}

	public String getDep() {
		return dep;
	}

	public void setDep(String dep) {
		this.dep = dep;
	}

	public String getDepdesc() {
		return depdesc;
	}

	public void setDepdesc(String depdesc) {
		this.depdesc = depdesc;
	}

	public String getGetday() {
		return getday;
	}

	public void setGetday(String getday) {
		this.getday = getday;
	}

	public ArrayList getArrayl() {
		return arrayl;
	}

	public void setArrayl(ArrayList arrayl) {
		this.arrayl = arrayl;
	}

	public ArrayList getAr_id() {
		return ar_id;
	}

	public void setAr_id(ArrayList ar_id) {
		this.ar_id = ar_id;
	}

	public ArrayList getAr_name() {
		return ar_name;
	}

	public void setAr_name(ArrayList ar_name) {
		this.ar_name = ar_name;
	}

	
	
	
	
	
}