/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.microlabs.main.form;

import org.apache.struts.action.ActionForm;
import org.apache.struts.upload.FormFile;

import java.util.ArrayList;
import java.util.LinkedList;

/** 
 * MyEclipse Struts
 * Creation date: 02-13-2013
 * 
 * XDoclet definition:
 * @struts.form name="approvalsForm"
 */

public class ApprovalsForm extends ActionForm {
	
	
	LinkedList leaveReason=new LinkedList();
	LinkedList leaveDetReason=new LinkedList();
	
	private String toDate;
	private String typeOfTravel;
	private String fromPlace;
	private String toPlace;
	private String departOn;
	private String departTime;
	
	private String requestName;
	private String oldId;
	private String newId;
	private String roleId;
	
	
	
	
	public String getRequestName() {
		return requestName;
	}

	public void setRequestName(String requestName) {
		this.requestName = requestName;
	}

	public String getOldId() {
		return oldId;
	}

	public void setOldId(String oldId) {
		this.oldId = oldId;
	}

	public String getNewId() {
		return newId;
	}

	public void setNewId(String newId) {
		this.newId = newId;
	}

	public String getRoleId() {
		return roleId;
	}

	public void setRoleId(String roleId) {
		this.roleId = roleId;
	}

	public String getToDate() {
		return toDate;
	}

	public void setToDate(String toDate) {
		this.toDate = toDate;
	}
	//Conference
	private String selectedFilterMat;
	public String getSelectedFilterMat() {
		return selectedFilterMat;
	}

	public void setSelectedFilterMat(String selectedFilterMat) {
		this.selectedFilterMat = selectedFilterMat;
	}
	private String gstinNo;
	
	public String getGstinNo() {
		return gstinNo;
	}

	public void setGstinNo(String gstinNo) {
		this.gstinNo = gstinNo;
	}
	private String sacCode;
	public String getSacCode() {
		return sacCode;
	}

	public void setSacCode(String sacCode) {
		this.sacCode = sacCode;
	}
	private String hsnCode;
	

	
	public String getHsnCode() {
		return hsnCode;
	}

	public void setHsnCode(String hsnCode) {
		this.hsnCode = hsnCode;
	}
	private String role;
	public String getRole() {
		return role;
	}

	public void setRole(String role) {
		this.role = role;
	}
	private String floor;
	private String roomName;
	private String fromDate;
	private String fromTime;
	private String timeTo;
	private String toTime;
	//IT REQUEST
		//Ad User Creation
		
		private String lastApprover;
		public String getTypeOfTravel() {
			return typeOfTravel;
		}

		public void setTypeOfTravel(String typeOfTravel) {
			this.typeOfTravel = typeOfTravel;
		}

		public String getFromPlace() {
			return fromPlace;
		}

		public void setFromPlace(String fromPlace) {
			this.fromPlace = fromPlace;
		}

		public String getToPlace() {
			return toPlace;
		}

		public void setToPlace(String toPlace) {
			this.toPlace = toPlace;
		}

		public String getDepartOn() {
			return departOn;
		}

		public void setDepartOn(String departOn) {
			this.departOn = departOn;
		}

		public String getDepartTime() {
			return departTime;
		}

		public void setDepartTime(String departTime) {
			this.departTime = departTime;
		}
		private String pendingApprover;
		
		private String requestedforname;
		private String requestedfordepartment;
		private String requestedfordesignation;
		private String requestedforlocation;

		private String requestStatus;
		private String requestername;
		private String requesterdepartment;
		private String requesterdesignation;
		private String location;

		private String usage;
		private String employeeno;
		


		private String mobno;
		private String extno;
		private String ipPhoneno;
		
		private String assetvalue;
		private ArrayList assetvalueIdList=new ArrayList();
		private ArrayList assetvalueLabelList=new ArrayList();
		
		private String hostname;
		private String IPNumber;
		private String adloginname;
		private String reqdfolderacces;
		
		private String message1;
		private String category;
		private String subcategory;
		private String newlyJoinedYes;
		private String newlyJoinedNo;
		private String joiningDate;
		private String totalIDs;
		private String deletedDBYes;
		private String deletedDBNo;
		private String forward_MailID;
		private String mailIDPath;
		private String initials;
		//Ad deletion
		
			private String deletefrom;
			private String reqdfolderdeletion;	
			
			
			
			//Ad transfer
			
			private ArrayList departmentList= new ArrayList();
			
			private String fromlocationId;
			private String tolocationId;
			
			private String  fromdepartment;
			private String  todepartment;
		
		//Lotus Id Creation
		private String reportingManager;
		private String isHeHod;
		private String suggestedEmailId;
		private String isthisCommonId;
		private String enablewebAccess;
		
		private int totalmailIdDept;
		private int totalmailIdloc;
		private String outsidecom;
		private String outsidecomyes;
		private String outsidecomno;
		private String firstname;
		private String lastname;
		private String middname;
		
		
		//Lotus Id Change
		private String fromemailId;
		private String empno;
		private String reasonforchange;
		private String transferoldmail;
		private String deleteoldmails;
		
		//lotus deletion
		private String emailidDelete;
		
		//Internet Access
		private String internetgrp;
		
		//external Drives 
		private String cdrom;
		private String usb;
		private String floppy;
		private String accesstype;
		private String devicetype;
		
		//FTP ACCESS
		private String requiredfoldername;
		private String durationofaccess;
		private String frmdurationofaccess;
		private String todurationofaccess;
		private String username;
		private String password;
		private String server;
		private String foldername;
		
		
		private String accesstypes[];
		//new Asset
				private String assetcategory;
				private String suggestmodelname;
				private String reqbydate;
				private String gxpyes;
				private String gxpno;
				private String typeofprinter;
				private String printvolpermonth;
				private String users;
				private String suggestmodelno;
				private String apprxvalue;
				private String lanyes;
				private String lanno;
				private String anysplreq;
		
	private String itType;
	private String reqPriority;
	private String remarks;
	private String itEngStatus;
	private String requestNo;
	private String requestDate;
	private String requestType;
	private String reqMaterialGroup;
	private String requestedBy;
	private String header;
	
	private String jobTitle;
	private String department;
	private String primaryLocation;
	
	private String remark;
	
	private String jobDescription;
	private String empStatus;
	private String totalEmp;
	private String qualifications;
	private String experience;
	private String saleryOffered;
	private String reqStatus;
	private String appMessage;
	
	private int totalAppCount;
	private int startAppCount;
	private int endAppCount;
	private LinkedList filterType;
	private String selectedFilter;
	private String fileNameList;
	private String reqRequstType;
	
	private String sapCodeNo;
	private String sapCodeExists;
	private String sapCodeExistsNo;
	private String sapCreationDate;
	private String sapCreatedBy;
	
	private String heading;
	private String searchText;
	private String method;
	
	private int totalRecords;
	private int startRecord;
	private int endRecord;
	private String[] selectedRequestNo;
	private String message;
	private String message3;

	
	private ArrayList locationIdList=new ArrayList();
	private ArrayList locationLabelList=new ArrayList();
	private LinkedList storageID;
	private LinkedList storageIDName;
	private LinkedList materTypeIDList;
	private LinkedList materialTypeIdValueList;
	private LinkedList materGroupIDList;
	private LinkedList materialGroupIdValueList;
	private LinkedList unitOfMeasIdList;
	private LinkedList unitOfMeasIdValues;
	private LinkedList pharmacopGradeIDList;
	private LinkedList pharmacopGradeValueList;
	private LinkedList valuationClassID;
	private LinkedList valuationClassName;
	private LinkedList dmfGradeIDList;
	private LinkedList dmfGradeIDValueList;
	private LinkedList counID;
	private LinkedList countryName;
	private LinkedList puchaseGroupIdList;
	private LinkedList puchaseGroupIdValues;
	private LinkedList sapCodeNoIdList;
	private LinkedList sapCodeNoIdValues;
	private LinkedList tempIDList;
	private LinkedList temValueList;
	private LinkedList storageIDList;
	private LinkedList storageLocList;
	private String shortName;
	private String longName;
	private String codeNo;
	private String materialType;
	private String materialGrup;
	
	//vendor search
	private String accountGroup;
	private String vendorType;
	private String vendorName;
	private String vendorAddress;
	private String vendorCity;
	
	//permission
	private String startTime;
	private String endTime;
	
	//onduty details
	
	private String onDutyType;
	
	private String duration;
	private String startDate;
	private String startDurationType;
	private String endDate;
	private String submitDate;
	private String endDurationType;
	private String noOfDays;
	private String documentName;
	private String fileName;
	private String id;
	private FormFile documentFile;
	private String generatedBy;
	private String status;
	public String[] leaveCheck;
	public String[] leavelist;
	private String reason;
	private String holidayType;
	
	private String approver;
	private String employeeNumber;
	private String designation;
	private String approverNumber;
	

	
	private int onDTotal;
	private int vpTotal;
	private int acTotal;
	private int cvTotal;
	private int tourTotal;
	
	private String locationId;
	private String storageLocationId;
	private String materialTypeId;
	private String materialShortName;
	private String materialLongName;
	private String materialGroupId;
	private String pharmacopName;
	private String pharmacopGrade;
	private String genericName;
	private String synonym;
	private String pharmacopSpecification;
	private String isDMFMaterial;
	private String shelfLifeType;
	private String retestType;
	
	private String dmfGradeId;
	private String materialGrade;
	private String cosGradeNo;
	private String additionalTest;
	private String countryId;
	private String customerName;
	private String toBeUsedInProducts;
	private String isVendorSpecificMaterial;
	private String mfgrName;
	private String siteOfManufacture;
	private String tempCondition;
	private String storageCondition;
	private String shelfLife;
	private String dutyElement;
	private String retestDays;
	private String valuationClass;
	private String approximateValue;
	private String unitOfMeasId;
	private String puchaseGroupId;
	
	private String message2;
	
	private String requestNumber;
	private String requestsearchDate;
	private String locationSearch;
	
	private String comments;
	private String userRole;
	private String priority;
	
	FormFile fileNames;
	private String fileList;
	private String url;
	
	private String materialCodeLists;
	private String materialCodeLists1;
	
	private String approveType;
	
	private String requiredRequestNumber;
	private String employeeCode;
	private String employeeName;
	private String approveStatus;
	private String date;
	
	
	//Finished Product
	private String manufacturedAt;
	private String shelfType;
	private String standardBatchSize;
	private String batchCode;
	private String saleableOrSample;
	private String domesticOrExports;
	private String salesPackId;
	private String packTypeId;
	private String therapeuticSegmentID;
	private String divisionId;
	private String brandID;
	private String srengthId;
	private String prodInspMemo;
	private String grossWeight;
	private String netWeight;
	private String weightUOM;
	private String dimension;
	private String salesUnitOfMeaseurement;
	private String typeDetails;
	private LinkedList packSizeID;
	private LinkedList packSizeName;
	private LinkedList packTypeID;
	private LinkedList packTypeName;
	private LinkedList salesUOMID;
	private LinkedList salesUOMName;
	private LinkedList divisonID;
	private LinkedList divisonName;
	private LinkedList therapeuticID;
	private LinkedList therapeuticName;
	private LinkedList brandIDList;
	private LinkedList brandNameList;
	private LinkedList strengthIDList;
	private LinkedList strengthNameList;
	private LinkedList genericIDList;
	private LinkedList genericNameList;
	private LinkedList weightUOMID;
	private LinkedList weightUOMName;
	private String taxClassification;
	private String materialPricing;
	private String matType;
	
	//VERP
	private String packageMaterialGroup;
	private String typeOfMaterial;
	
	private String artworkNo;
	
	private String isArtworkRevision;
	private String  existingSAPItemCode;
	private LinkedList packageGroupID;
	private LinkedList packageGroupIDValue;
	
	
	//semifinished
	
	private String packSize;
	private String targetWeight;
	
	//promotional
	private String isSASFormAvailable;
	private String isAsset;
	
	
	//ZPSR
	
	private String moc;
	private String rating;
	private String range;
	private String materialUsedIn;
	private String isEquipment;
	private String isSpare;
	private String isNewEquipment;
	private String isItNewFurniture;
	private String isItFacility;
	private String isSpareNewEquipment;
	
	
	
	private String equipmentName;
	private String prNumber;
	private String poNumber;
	private String utilizingDept;
	private String detailedJustification;
	private String detailedSpecification;
	private String purposeID;
	private LinkedList deptId;
	private LinkedList deptName;
	private String equipmentMake;
	private String componentMake;
	private String oemPartNo;
	private String equipIntendedFor;
	//service Master
	
	private String materialtype;
	private String material_des;
	private String materialGroup;
	private String materialPlant;
	private String locationID;
	
	private String serviceRequestDate;
	
	
	private String servicePlant;
	private String serviceSatus;
	private String serviceRequestedBy;
	private String serviceApproveDate;
	
	private String customerRequestDate;
	private String customerLocation;
	private String c_country;
	private String c_customerGroup;
	private String c_status;
	
	private int r_no;
	private String plantCode;
	private String storageLocation;
	private String serviceDescription;
	private String detailedServiceDescription;
	private String uom;
	private String purchaseGroup;
	private String serviceCatagory;
	private String serviceGroup;
	private String e_m_name;
	private String app_amount;
	private String whereUsed;
	private String purpose;
	private String justification;
	private FormFile serviceAttachment;
	private String approveDate;
	//private String requestedBy;
	//private String approveDate;
	private String[] documentCheck;
	private String filepath;
	
	private String u_id;
	private String u_label;
	
	private String p_id;
	private String p_all;
	
	private String pl_id;
	private String pl_all;
	
	private String service_id;
	private String service_label;
	private String sfile;
	
	private LinkedList<Object> uomId;
	private LinkedList uomLabel;
	
	private LinkedList pid;
	private LinkedList plabel;
	
	private LinkedList vid;
	private LinkedList vlabel;
	
	private LinkedList pcode; 
	
	
	private LinkedList sgroupLabel;
	
	private LinkedList serviceGroupID;
	private LinkedList serviceGroupValues;
	
	//code extention
	
	private String plant1;
	private String materialCode1;
	private String extendToPlant1;
	private String storageLocationId1;
 	private String plantType;
 	private String extendToStorageLocation1;
 	private String plant2;
	private String materialCode2;
	private String fromStorageLocation;
	private String toStorageLocation;
	
	
	//vendor master
	
	private String accountGroupId;
	
	private String purchaseView;
	private String title;
	private String name;
	private String address1;
	private String address2;
	private String address3;
	private String address4;
	private String city;
	private String pinCode;
	private String country;
	private String state;
	private String landLineNo;
	private String mobileNo;
	private String faxNo;
	private String emailId;
	private String currencyId;
	private String reConcillationActId;
	private String elgTds;
	private String tdsCode;
	private String lstNo;
	private String tinNo;
	private String cstNo;
	private String panNo;
	private String serviceTaxRegNo;
	private String regExciseVendor;
	private String eccNo;
	private String exciseRegNo;
	private String linkName;
	private String exciseRange;
	private String exciseDivision;
	private String paymentTermId;
	private String accountClerkId;
	private String isApprovedVendor;
	private FormFile vendorAttachments;
	private String contentDescription;
	private String fileFullPath;
	private String videoFullPath;

	private String commissionerate;
	private String typeOfVendor;

	private ArrayList accountGroupList=new ArrayList();
	private ArrayList accountGroupLabelList=new ArrayList();
	
	
	
	private ArrayList countryList=new ArrayList();
	private ArrayList countryLabelList=new ArrayList();
	
	private ArrayList stateList=new ArrayList();
	private ArrayList stateLabelList=new ArrayList();
	
	private ArrayList currencyList=new ArrayList();
	private ArrayList currencyLabelList=new ArrayList();
	
	private ArrayList reConcillationList=new ArrayList();
	private ArrayList reConcillationLabelList=new ArrayList();
	
	private ArrayList paymentTermList=new ArrayList();
	private ArrayList paymentTermLabelList=new ArrayList();
	
	private ArrayList accountClerkList=new ArrayList();
	private ArrayList accountClerkLabelList=new ArrayList();
	
	private ArrayList tdsIdList=new ArrayList();
	private ArrayList tdsLabelList=new ArrayList();
	private String accountView;
	
	
	//CUSTOMER
	
	
	private String accGroupId;
	private String viewType;

	private String pincode;

	private String landlineNo;
	private String customerGroup;
	private String priceGroup;
	private String priceList;
	private String taxType;
	private String listNumber;
	
	private String tinNumber;
	private String cstNumber;
	private String panNumber;
	private String serviceTaxNo;
	private String isRegdExciseVender;
	private String dlno1;
	private String dlno2;
	private String paymentTermID;
	private String createdDate;
	private String createdBy;
	private String modifiedDate;

	private String custmerType;
	private String tdsStatus;


	private String sales;
	private String accounts;
	private String domestic;
	private String exports;
	private String customerType;
	private String cutomerCode;

	private String searchRequired;

	private LinkedList stateId;
	private LinkedList states;
	
	private LinkedList currenIds;
	private LinkedList currencys;
	
	private LinkedList tdsIds;
	private LinkedList tdsCodes;

	private LinkedList cusGroupID;
	private LinkedList cusGroupList;
	
	private LinkedList priceGroupID;
	private LinkedList piceGroupList;
	
	private LinkedList priceListID;
	private LinkedList piceListValue;
	
	private LinkedList taxTypeID;
	private LinkedList taxTypeValue;
	private String mailIDRetained;
	
	
	// sap related
		private String techniciansID;
		private String mode;
		private String subject;
		
		private String category1;
		private String subcategory1;
		
		
		private String storage;
		private String toItperson;
		
		
		//qms 
		
		private String user;
		private String multilocation[];
		private String multilocationid;
		private String view;
		
		private String type;
		
		
		private String swipetype;
		
		
		private ArrayList deptList=new ArrayList();
		private ArrayList deptLabelList=new ArrayList();
		
		

		private ArrayList desgList=new ArrayList();
		private ArrayList desgLabelList=new ArrayList();
		
		
		
	private String chooseKeyword;
		
		
	
	private String firstName;
	private String gender;
	private String dateofBirth;
		
	private String reasonType;
	
	
	
	
		public String getFirstName() {
		return firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getGender() {
		return gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	public String getDateofBirth() {
		return dateofBirth;
	}

	public void setDateofBirth(String dateofBirth) {
		this.dateofBirth = dateofBirth;
	}

	public String getReasonType() {
		return reasonType;
	}

	public void setReasonType(String reasonType) {
		this.reasonType = reasonType;
	}

		public String getChooseKeyword() {
			return chooseKeyword;
		}

		public void setChooseKeyword(String chooseKeyword) {
			this.chooseKeyword = chooseKeyword;
		}

		
		public ArrayList getDeptList() {
			return deptList;
		}

		public void setDeptList(ArrayList deptList) {
			this.deptList = deptList;
		}

		public ArrayList getDeptLabelList() {
			return deptLabelList;
		}

		public void setDeptLabelList(ArrayList deptLabelList) {
			this.deptLabelList = deptLabelList;
		}

		public ArrayList getDesgList() {
			return desgList;
		}

		public void setDesgList(ArrayList desgList) {
			this.desgList = desgList;
		}

		public ArrayList getDesgLabelList() {
			return desgLabelList;
		}

		public void setDesgLabelList(ArrayList desgLabelList) {
			this.desgLabelList = desgLabelList;
		}
		
		
		
		public String getSwipetype() {
			return swipetype;
		}

		public void setSwipetype(String swipetype) {
			this.swipetype = swipetype;
		}

		public String getType() {
			return type;
		}

		public void setType(String type) {
			this.type = type;
		}

		public String getUser() {
			return user;
		}

		public void setUser(String user) {
			this.user = user;
		}

		public String[] getMultilocation() {
			return multilocation;
		}

		public void setMultilocation(String[] multilocation) {
			this.multilocation = multilocation;
		}

		public String getMultilocationid() {
			return multilocationid;
		}

		public void setMultilocationid(String multilocationid) {
			this.multilocationid = multilocationid;
		}

		public String getView() {
			return view;
		}

		public void setView(String view) {
			this.view = view;
		}

		public String getToItperson() {
			return toItperson;
		}

		public void setToItperson(String toItperson) {
			this.toItperson = toItperson;
		}

		
	
	public String getStorage() {
			return storage;
		}
		public void setStorage(String storage) {
			this.storage = storage;
		}
	public String getTechniciansID() {
			return techniciansID;
		}
		public void setTechniciansID(String techniciansID) {
			this.techniciansID = techniciansID;
		}
		public String getMode() {
			return mode;
		}
		public void setMode(String mode) {
			this.mode = mode;
		}
		public String getSubject() {
			return subject;
		}
		public void setSubject(String subject) {
			this.subject = subject;
		}
		public String getCategory1() {
			return category1;
		}
		public void setCategory1(String category1) {
			this.category1 = category1;
		}
		public String getSubcategory1() {
			return subcategory1;
		}
		public void setSubcategory1(String subcategory1) {
			this.subcategory1 = subcategory1;
		}
	public String getRequestedforname() {
		return requestedforname;
	}
	public void setRequestedforname(String requestedforname) {
		this.requestedforname = requestedforname;
	}
	public String getRequestedfordepartment() {
		return requestedfordepartment;
	}
	public void setRequestedfordepartment(String requestedfordepartment) {
		this.requestedfordepartment = requestedfordepartment;
	}
	public String getRequestedfordesignation() {
		return requestedfordesignation;
	}
	public void setRequestedfordesignation(String requestedfordesignation) {
		this.requestedfordesignation = requestedfordesignation;
	}
	public String getRequestedforlocation() {
		return requestedforlocation;
	}
	public void setRequestedforlocation(String requestedforlocation) {
		this.requestedforlocation = requestedforlocation;
	}
	public LinkedList getLeaveReason() {
		return leaveReason;
	}
	public void setLeaveReason(LinkedList leaveReason) {
		this.leaveReason = leaveReason;
	}
	public LinkedList getLeaveDetReason() {
		return leaveDetReason;
	}
	public void setLeaveDetReason(LinkedList leaveDetReason) {
		this.leaveDetReason = leaveDetReason;
	}
	public String[] getAccesstypes() {
		return accesstypes;
	}
	public void setAccesstypes(String[] accesstypes) {
		this.accesstypes = accesstypes;
	}
	public String getToTime() {
		return toTime;
	}
	public void setToTime(String toTime) {
		this.toTime = toTime;
	}
	public String getFloor() {
		return floor;
	}
	public void setFloor(String floor) {
		this.floor = floor;
	}
	public String getRoomName() {
		return roomName;
	}
	public void setRoomName(String roomName) {
		this.roomName = roomName;
	}
	public String getFromDate() {
		return fromDate;
	}
	public void setFromDate(String fromDate) {
		this.fromDate = fromDate;
	}
	public String getFromTime() {
		return fromTime;
	}
	public void setFromTime(String fromTime) {
		this.fromTime = fromTime;
	}
	public String getTimeTo() {
		return timeTo;
	}
	public void setTimeTo(String timeTo) {
		this.timeTo = timeTo;
	}
	public String getAssetcategory() {
		return assetcategory;
	}
	public void setAssetcategory(String assetcategory) {
		this.assetcategory = assetcategory;
	}
	public String getSuggestmodelname() {
		return suggestmodelname;
	}
	public void setSuggestmodelname(String suggestmodelname) {
		this.suggestmodelname = suggestmodelname;
	}
	public String getReqbydate() {
		return reqbydate;
	}
	public void setReqbydate(String reqbydate) {
		this.reqbydate = reqbydate;
	}
	public String getGxpyes() {
		return gxpyes;
	}
	public void setGxpyes(String gxpyes) {
		this.gxpyes = gxpyes;
	}
	public String getGxpno() {
		return gxpno;
	}
	public void setGxpno(String gxpno) {
		this.gxpno = gxpno;
	}
	public String getTypeofprinter() {
		return typeofprinter;
	}
	public void setTypeofprinter(String typeofprinter) {
		this.typeofprinter = typeofprinter;
	}
	public String getPrintvolpermonth() {
		return printvolpermonth;
	}
	public void setPrintvolpermonth(String printvolpermonth) {
		this.printvolpermonth = printvolpermonth;
	}
	public String getUsers() {
		return users;
	}
	public void setUsers(String users) {
		this.users = users;
	}
	public String getSuggestmodelno() {
		return suggestmodelno;
	}
	public void setSuggestmodelno(String suggestmodelno) {
		this.suggestmodelno = suggestmodelno;
	}
	public String getApprxvalue() {
		return apprxvalue;
	}
	public void setApprxvalue(String apprxvalue) {
		this.apprxvalue = apprxvalue;
	}
	public String getLanyes() {
		return lanyes;
	}
	public void setLanyes(String lanyes) {
		this.lanyes = lanyes;
	}
	public String getLanno() {
		return lanno;
	}
	public void setLanno(String lanno) {
		this.lanno = lanno;
	}
	public String getAnysplreq() {
		return anysplreq;
	}
	public void setAnysplreq(String anysplreq) {
		this.anysplreq = anysplreq;
	}
	public String getInitials() {
		return initials;
	}
	public void setInitials(String initials) {
		this.initials = initials;
	}
	public String getDeletedDBYes() {
		return deletedDBYes;
	}
	public void setDeletedDBYes(String deletedDBYes) {
		this.deletedDBYes = deletedDBYes;
	}
	public String getDeletedDBNo() {
		return deletedDBNo;
	}
	public void setDeletedDBNo(String deletedDBNo) {
		this.deletedDBNo = deletedDBNo;
	}
	public String getForward_MailID() {
		return forward_MailID;
	}
	public void setForward_MailID(String forward_MailID) {
		this.forward_MailID = forward_MailID;
	}
	public String getMailIDPath() {
		return mailIDPath;
	}
	public void setMailIDPath(String mailIDPath) {
		this.mailIDPath = mailIDPath;
	}
	public String getMailIDRetained() {
		return mailIDRetained;
	}
	public void setMailIDRetained(String mailIDRetained) {
		this.mailIDRetained = mailIDRetained;
	}
	public String getNewlyJoinedYes() {
		return newlyJoinedYes;
	}
	public void setNewlyJoinedYes(String newlyJoinedYes) {
		this.newlyJoinedYes = newlyJoinedYes;
	}
	public String getNewlyJoinedNo() {
		return newlyJoinedNo;
	}
	public void setNewlyJoinedNo(String newlyJoinedNo) {
		this.newlyJoinedNo = newlyJoinedNo;
	}
	public String getJoiningDate() {
		return joiningDate;
	}
	public void setJoiningDate(String joiningDate) {
		this.joiningDate = joiningDate;
	}
	public String getTotalIDs() {
		return totalIDs;
	}
	public void setTotalIDs(String totalIDs) {
		this.totalIDs = totalIDs;
	}
	public String getCategory() {
		return category;
	}
	public void setCategory(String category) {
		this.category = category;
	}
	public String getSubcategory() {
		return subcategory;
	}
	public void setSubcategory(String subcategory) {
		this.subcategory = subcategory;
	}
	public String getLastApprover() {
		return lastApprover;
	}
	public void setLastApprover(String lastApprover) {
		this.lastApprover = lastApprover;
	}
	public String getPendingApprover() {
		return pendingApprover;
	}
	public void setPendingApprover(String pendingApprover) {
		this.pendingApprover = pendingApprover;
	}
	public String getRequestStatus() {
		return requestStatus;
	}
	public void setRequestStatus(String requestStatus) {
		this.requestStatus = requestStatus;
	}
	public String getRequestername() {
		return requestername;
	}
	public void setRequestername(String requestername) {
		this.requestername = requestername;
	}
	public String getRequesterdepartment() {
		return requesterdepartment;
	}
	public void setRequesterdepartment(String requesterdepartment) {
		this.requesterdepartment = requesterdepartment;
	}
	public String getRequesterdesignation() {
		return requesterdesignation;
	}
	public void setRequesterdesignation(String requesterdesignation) {
		this.requesterdesignation = requesterdesignation;
	}
	public String getLocation() {
		return location;
	}
	public void setLocation(String location) {
		this.location = location;
	}
	public String getUsage() {
		return usage;
	}
	public void setUsage(String usage) {
		this.usage = usage;
	}
	public String getEmployeeno() {
		return employeeno;
	}
	public void setEmployeeno(String employeeno) {
		this.employeeno = employeeno;
	}
	public String getMobno() {
		return mobno;
	}
	public void setMobno(String mobno) {
		this.mobno = mobno;
	}
	public String getExtno() {
		return extno;
	}
	public void setExtno(String extno) {
		this.extno = extno;
	}
	public String getIpPhoneno() {
		return ipPhoneno;
	}
	public void setIpPhoneno(String ipPhoneno) {
		this.ipPhoneno = ipPhoneno;
	}
	public String getAssetvalue() {
		return assetvalue;
	}
	public void setAssetvalue(String assetvalue) {
		this.assetvalue = assetvalue;
	}
	public ArrayList getAssetvalueIdList() {
		return assetvalueIdList;
	}
	public void setAssetvalueIdList(ArrayList assetvalueIdList) {
		this.assetvalueIdList = assetvalueIdList;
	}
	public ArrayList getAssetvalueLabelList() {
		return assetvalueLabelList;
	}
	public void setAssetvalueLabelList(ArrayList assetvalueLabelList) {
		this.assetvalueLabelList = assetvalueLabelList;
	}
	public String getHostname() {
		return hostname;
	}
	public void setHostname(String hostname) {
		this.hostname = hostname;
	}
	public String getIPNumber() {
		return IPNumber;
	}
	public void setIPNumber(String iPNumber) {
		IPNumber = iPNumber;
	}
	public String getAdloginname() {
		return adloginname;
	}
	public void setAdloginname(String adloginname) {
		this.adloginname = adloginname;
	}
	public String getReqdfolderacces() {
		return reqdfolderacces;
	}
	public void setReqdfolderacces(String reqdfolderacces) {
		this.reqdfolderacces = reqdfolderacces;
	}
	public String getMessage1() {
		return message1;
	}
	public void setMessage1(String message1) {
		this.message1 = message1;
	}
	public String getDeletefrom() {
		return deletefrom;
	}
	public void setDeletefrom(String deletefrom) {
		this.deletefrom = deletefrom;
	}
	public String getReqdfolderdeletion() {
		return reqdfolderdeletion;
	}
	public void setReqdfolderdeletion(String reqdfolderdeletion) {
		this.reqdfolderdeletion = reqdfolderdeletion;
	}
	public ArrayList getDepartmentList() {
		return departmentList;
	}
	public void setDepartmentList(ArrayList departmentList) {
		this.departmentList = departmentList;
	}
	public String getFromlocationId() {
		return fromlocationId;
	}
	public void setFromlocationId(String fromlocationId) {
		this.fromlocationId = fromlocationId;
	}
	public String getTolocationId() {
		return tolocationId;
	}
	public void setTolocationId(String tolocationId) {
		this.tolocationId = tolocationId;
	}
	public String getFromdepartment() {
		return fromdepartment;
	}
	public void setFromdepartment(String fromdepartment) {
		this.fromdepartment = fromdepartment;
	}
	public String getTodepartment() {
		return todepartment;
	}
	public void setTodepartment(String todepartment) {
		this.todepartment = todepartment;
	}
	public String getReportingManager() {
		return reportingManager;
	}
	public void setReportingManager(String reportingManager) {
		this.reportingManager = reportingManager;
	}
	public String getIsHeHod() {
		return isHeHod;
	}
	public void setIsHeHod(String isHeHod) {
		this.isHeHod = isHeHod;
	}
	public String getSuggestedEmailId() {
		return suggestedEmailId;
	}
	public void setSuggestedEmailId(String suggestedEmailId) {
		this.suggestedEmailId = suggestedEmailId;
	}
	public String getIsthisCommonId() {
		return isthisCommonId;
	}
	public void setIsthisCommonId(String isthisCommonId) {
		this.isthisCommonId = isthisCommonId;
	}
	public String getEnablewebAccess() {
		return enablewebAccess;
	}
	public void setEnablewebAccess(String enablewebAccess) {
		this.enablewebAccess = enablewebAccess;
	}
	public int getTotalmailIdDept() {
		return totalmailIdDept;
	}
	public void setTotalmailIdDept(int totalmailIdDept) {
		this.totalmailIdDept = totalmailIdDept;
	}
	public int getTotalmailIdloc() {
		return totalmailIdloc;
	}
	public void setTotalmailIdloc(int totalmailIdloc) {
		this.totalmailIdloc = totalmailIdloc;
	}
	public String getOutsidecom() {
		return outsidecom;
	}
	public void setOutsidecom(String outsidecom) {
		this.outsidecom = outsidecom;
	}
	public String getOutsidecomyes() {
		return outsidecomyes;
	}
	public void setOutsidecomyes(String outsidecomyes) {
		this.outsidecomyes = outsidecomyes;
	}
	public String getOutsidecomno() {
		return outsidecomno;
	}
	public void setOutsidecomno(String outsidecomno) {
		this.outsidecomno = outsidecomno;
	}
	public String getFirstname() {
		return firstname;
	}
	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}
	public String getLastname() {
		return lastname;
	}
	public void setLastname(String lastname) {
		this.lastname = lastname;
	}
	public String getMiddname() {
		return middname;
	}
	public void setMiddname(String middname) {
		this.middname = middname;
	}
	public String getFromemailId() {
		return fromemailId;
	}
	public void setFromemailId(String fromemailId) {
		this.fromemailId = fromemailId;
	}
	public String getEmpno() {
		return empno;
	}
	public void setEmpno(String empno) {
		this.empno = empno;
	}
	public String getReasonforchange() {
		return reasonforchange;
	}
	public void setReasonforchange(String reasonforchange) {
		this.reasonforchange = reasonforchange;
	}
	public String getTransferoldmail() {
		return transferoldmail;
	}
	public void setTransferoldmail(String transferoldmail) {
		this.transferoldmail = transferoldmail;
	}
	public String getDeleteoldmails() {
		return deleteoldmails;
	}
	public void setDeleteoldmails(String deleteoldmails) {
		this.deleteoldmails = deleteoldmails;
	}
	public String getEmailidDelete() {
		return emailidDelete;
	}
	public void setEmailidDelete(String emailidDelete) {
		this.emailidDelete = emailidDelete;
	}
	public String getInternetgrp() {
		return internetgrp;
	}
	public void setInternetgrp(String internetgrp) {
		this.internetgrp = internetgrp;
	}
	public String getCdrom() {
		return cdrom;
	}
	public void setCdrom(String cdrom) {
		this.cdrom = cdrom;
	}
	public String getUsb() {
		return usb;
	}
	public void setUsb(String usb) {
		this.usb = usb;
	}
	public String getFloppy() {
		return floppy;
	}
	public void setFloppy(String floppy) {
		this.floppy = floppy;
	}
	public String getAccesstype() {
		return accesstype;
	}
	public void setAccesstype(String accesstype) {
		this.accesstype = accesstype;
	}
	public String getDevicetype() {
		return devicetype;
	}
	public void setDevicetype(String devicetype) {
		this.devicetype = devicetype;
	}
	public String getRequiredfoldername() {
		return requiredfoldername;
	}
	public void setRequiredfoldername(String requiredfoldername) {
		this.requiredfoldername = requiredfoldername;
	}
	public String getDurationofaccess() {
		return durationofaccess;
	}
	public void setDurationofaccess(String durationofaccess) {
		this.durationofaccess = durationofaccess;
	}
	public String getFrmdurationofaccess() {
		return frmdurationofaccess;
	}
	public void setFrmdurationofaccess(String frmdurationofaccess) {
		this.frmdurationofaccess = frmdurationofaccess;
	}
	public String getTodurationofaccess() {
		return todurationofaccess;
	}
	public void setTodurationofaccess(String todurationofaccess) {
		this.todurationofaccess = todurationofaccess;
	}
	public String getUsername() {
		return username;
	}
	public void setUsername(String username) {
		this.username = username;
	}
	public String getPassword() {
		return password;
	}
	public void setPassword(String password) {
		this.password = password;
	}
	public String getServer() {
		return server;
	}
	public void setServer(String server) {
		this.server = server;
	}
	public String getFoldername() {
		return foldername;
	}
	public void setFoldername(String foldername) {
		this.foldername = foldername;
	}
	public String getItType() {
		return itType;
	}
	public void setItType(String itType) {
		this.itType = itType;
	}
	public String getReqPriority() {
		return reqPriority;
	}
	public void setReqPriority(String reqPriority) {
		this.reqPriority = reqPriority;
	}
	public String getRemarks() {
		return remarks;
	}
	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}
	public String getItEngStatus() {
		return itEngStatus;
	}
	public void setItEngStatus(String itEngStatus) {
		this.itEngStatus = itEngStatus;
	}
	public String getMatType() {
		return matType;
	}
	public void setMatType(String matType) {
		this.matType = matType;
	}
	public String getEquipIntendedFor() {
		return equipIntendedFor;
	}
	public void setEquipIntendedFor(String equipIntendedFor) {
		this.equipIntendedFor = equipIntendedFor;
	}
	public String getAccountGroup() {
		return accountGroup;
	}
	public void setAccountGroup(String accountGroup) {
		this.accountGroup = accountGroup;
	}
	public String getVendorType() {
		return vendorType;
	}
	public void setVendorType(String vendorType) {
		this.vendorType = vendorType;
	}
	public String getVendorName() {
		return vendorName;
	}
	public void setVendorName(String vendorName) {
		this.vendorName = vendorName;
	}
	public String getVendorAddress() {
		return vendorAddress;
	}
	public void setVendorAddress(String vendorAddress) {
		this.vendorAddress = vendorAddress;
	}
	public String getVendorCity() {
		return vendorCity;
	}
	public void setVendorCity(String vendorCity) {
		this.vendorCity = vendorCity;
	}
	public String getShortName() {
		return shortName;
	}
	public void setShortName(String shortName) {
		this.shortName = shortName;
	}
	public String getLongName() {
		return longName;
	}
	public void setLongName(String longName) {
		this.longName = longName;
	}
	public String getCodeNo() {
		return codeNo;
	}
	public void setCodeNo(String codeNo) {
		this.codeNo = codeNo;
	}
	public String getMaterialType() {
		return materialType;
	}
	public void setMaterialType(String materialType) {
		this.materialType = materialType;
	}
	public String getMaterialGrup() {
		return materialGrup;
	}
	public void setMaterialGrup(String materialGrup) {
		this.materialGrup = materialGrup;
	}
	public String getStartTime() {
		return startTime;
	}
	public void setStartTime(String startTime) {
		this.startTime = startTime;
	}
	public String getEndTime() {
		return endTime;
	}
	public void setEndTime(String endTime) {
		this.endTime = endTime;
	}
	public String getOnDutyType() {
		return onDutyType;
	}
	public void setOnDutyType(String onDutyType) {
		this.onDutyType = onDutyType;
	}
	public String getDuration() {
		return duration;
	}
	public void setDuration(String duration) {
		this.duration = duration;
	}
	public String getStartDate() {
		return startDate;
	}
	public void setStartDate(String startDate) {
		this.startDate = startDate;
	}
	public String getStartDurationType() {
		return startDurationType;
	}
	public void setStartDurationType(String startDurationType) {
		this.startDurationType = startDurationType;
	}
	public String getEndDate() {
		return endDate;
	}
	public void setEndDate(String endDate) {
		this.endDate = endDate;
	}
	public String getSubmitDate() {
		return submitDate;
	}
	public void setSubmitDate(String submitDate) {
		this.submitDate = submitDate;
	}
	public String getEndDurationType() {
		return endDurationType;
	}
	public void setEndDurationType(String endDurationType) {
		this.endDurationType = endDurationType;
	}
	public String getNoOfDays() {
		return noOfDays;
	}
	public void setNoOfDays(String noOfDays) {
		this.noOfDays = noOfDays;
	}
	public String getDocumentName() {
		return documentName;
	}
	public void setDocumentName(String documentName) {
		this.documentName = documentName;
	}
	public String getFileName() {
		return fileName;
	}
	public void setFileName(String fileName) {
		this.fileName = fileName;
	}
	public String getId() {
		return id;
	}
	public void setId(String id) {
		this.id = id;
	}
	public FormFile getDocumentFile() {
		return documentFile;
	}
	public void setDocumentFile(FormFile documentFile) {
		this.documentFile = documentFile;
	}
	public String getGeneratedBy() {
		return generatedBy;
	}
	public void setGeneratedBy(String generatedBy) {
		this.generatedBy = generatedBy;
	}
	public String getStatus() {
		return status;
	}
	public void setStatus(String status) {
		this.status = status;
	}
	public String[] getLeaveCheck() {
		return leaveCheck;
	}
	public void setLeaveCheck(String[] leaveCheck) {
		this.leaveCheck = leaveCheck;
	}
	public String[] getLeavelist() {
		return leavelist;
	}
	public void setLeavelist(String[] leavelist) {
		this.leavelist = leavelist;
	}
	public String getReason() {
		return reason;
	}
	public void setReason(String reason) {
		this.reason = reason;
	}
	public String getHolidayType() {
		return holidayType;
	}
	public void setHolidayType(String holidayType) {
		this.holidayType = holidayType;
	}
	public String getApprover() {
		return approver;
	}
	public void setApprover(String approver) {
		this.approver = approver;
	}
	public String getEmployeeNumber() {
		return employeeNumber;
	}
	public void setEmployeeNumber(String employeeNumber) {
		this.employeeNumber = employeeNumber;
	}
	public String getDesignation() {
		return designation;
	}
	public void setDesignation(String designation) {
		this.designation = designation;
	}
	public String getApproverNumber() {
		return approverNumber;
	}
	public void setApproverNumber(String approverNumber) {
		this.approverNumber = approverNumber;
	}
	public int getOnDTotal() {
		return onDTotal;
	}
	public void setOnDTotal(int onDTotal) {
		this.onDTotal = onDTotal;
	}
	public int getVpTotal() {
		return vpTotal;
	}
	public void setVpTotal(int vpTotal) {
		this.vpTotal = vpTotal;
	}
	public int getAcTotal() {
		return acTotal;
	}
	public void setAcTotal(int acTotal) {
		this.acTotal = acTotal;
	}
	public int getCvTotal() {
		return cvTotal;
	}
	public void setCvTotal(int cvTotal) {
		this.cvTotal = cvTotal;
	}
	public int getTourTotal() {
		return tourTotal;
	}
	public void setTourTotal(int tourTotal) {
		this.tourTotal = tourTotal;
	}
	public String getMessage3() {
		return message3;
	}
	public void setMessage3(String message3) {
		this.message3 = message3;
	}
	public String getAccGroupId() {
		return accGroupId;
	}
	public void setAccGroupId(String accGroupId) {
		this.accGroupId = accGroupId;
	}
	public String getViewType() {
		return viewType;
	}
	public void setViewType(String viewType) {
		this.viewType = viewType;
	}
	public String getPincode() {
		return pincode;
	}
	public void setPincode(String pincode) {
		this.pincode = pincode;
	}
	public String getLandlineNo() {
		return landlineNo;
	}
	public void setLandlineNo(String landlineNo) {
		this.landlineNo = landlineNo;
	}
	public String getCustomerGroup() {
		return customerGroup;
	}
	public void setCustomerGroup(String customerGroup) {
		this.customerGroup = customerGroup;
	}
	public String getPriceGroup() {
		return priceGroup;
	}
	public void setPriceGroup(String priceGroup) {
		this.priceGroup = priceGroup;
	}
	public String getPriceList() {
		return priceList;
	}
	public void setPriceList(String priceList) {
		this.priceList = priceList;
	}
	public String getTaxType() {
		return taxType;
	}
	public void setTaxType(String taxType) {
		this.taxType = taxType;
	}
	public String getListNumber() {
		return listNumber;
	}
	public void setListNumber(String listNumber) {
		this.listNumber = listNumber;
	}
	public String getTinNumber() {
		return tinNumber;
	}
	public void setTinNumber(String tinNumber) {
		this.tinNumber = tinNumber;
	}
	public String getCstNumber() {
		return cstNumber;
	}
	public void setCstNumber(String cstNumber) {
		this.cstNumber = cstNumber;
	}
	public String getPanNumber() {
		return panNumber;
	}
	public void setPanNumber(String panNumber) {
		this.panNumber = panNumber;
	}
	public String getServiceTaxNo() {
		return serviceTaxNo;
	}
	public void setServiceTaxNo(String serviceTaxNo) {
		this.serviceTaxNo = serviceTaxNo;
	}
	public String getIsRegdExciseVender() {
		return isRegdExciseVender;
	}
	public void setIsRegdExciseVender(String isRegdExciseVender) {
		this.isRegdExciseVender = isRegdExciseVender;
	}
	public String getDlno1() {
		return dlno1;
	}
	public void setDlno1(String dlno1) {
		this.dlno1 = dlno1;
	}
	public String getDlno2() {
		return dlno2;
	}
	public void setDlno2(String dlno2) {
		this.dlno2 = dlno2;
	}
	public String getPaymentTermID() {
		return paymentTermID;
	}
	public void setPaymentTermID(String paymentTermID) {
		this.paymentTermID = paymentTermID;
	}
	public String getCreatedDate() {
		return createdDate;
	}
	public void setCreatedDate(String createdDate) {
		this.createdDate = createdDate;
	}
	public String getCreatedBy() {
		return createdBy;
	}
	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}
	public String getModifiedDate() {
		return modifiedDate;
	}
	public void setModifiedDate(String modifiedDate) {
		this.modifiedDate = modifiedDate;
	}
	public String getCustmerType() {
		return custmerType;
	}
	public void setCustmerType(String custmerType) {
		this.custmerType = custmerType;
	}
	public String getTdsStatus() {
		return tdsStatus;
	}
	public void setTdsStatus(String tdsStatus) {
		this.tdsStatus = tdsStatus;
	}
	public String getSales() {
		return sales;
	}
	public void setSales(String sales) {
		this.sales = sales;
	}
	public String getAccounts() {
		return accounts;
	}
	public void setAccounts(String accounts) {
		this.accounts = accounts;
	}
	public String getDomestic() {
		return domestic;
	}
	public void setDomestic(String domestic) {
		this.domestic = domestic;
	}
	public String getExports() {
		return exports;
	}
	public void setExports(String exports) {
		this.exports = exports;
	}
	public String getCustomerType() {
		return customerType;
	}
	public void setCustomerType(String customerType) {
		this.customerType = customerType;
	}
	public String getCutomerCode() {
		return cutomerCode;
	}
	public void setCutomerCode(String cutomerCode) {
		this.cutomerCode = cutomerCode;
	}
	public String getSearchRequired() {
		return searchRequired;
	}
	public void setSearchRequired(String searchRequired) {
		this.searchRequired = searchRequired;
	}
	public LinkedList getStateId() {
		return stateId;
	}
	public void setStateId(LinkedList stateId) {
		this.stateId = stateId;
	}
	public LinkedList getStates() {
		return states;
	}
	public void setStates(LinkedList states) {
		this.states = states;
	}
	public LinkedList getCurrenIds() {
		return currenIds;
	}
	public void setCurrenIds(LinkedList currenIds) {
		this.currenIds = currenIds;
	}
	public LinkedList getCurrencys() {
		return currencys;
	}
	public void setCurrencys(LinkedList currencys) {
		this.currencys = currencys;
	}
	public LinkedList getTdsIds() {
		return tdsIds;
	}
	public void setTdsIds(LinkedList tdsIds) {
		this.tdsIds = tdsIds;
	}
	public LinkedList getTdsCodes() {
		return tdsCodes;
	}
	public void setTdsCodes(LinkedList tdsCodes) {
		this.tdsCodes = tdsCodes;
	}
	public LinkedList getCusGroupID() {
		return cusGroupID;
	}
	public void setCusGroupID(LinkedList cusGroupID) {
		this.cusGroupID = cusGroupID;
	}
	public LinkedList getCusGroupList() {
		return cusGroupList;
	}
	public void setCusGroupList(LinkedList cusGroupList) {
		this.cusGroupList = cusGroupList;
	}
	public LinkedList getPriceGroupID() {
		return priceGroupID;
	}
	public void setPriceGroupID(LinkedList priceGroupID) {
		this.priceGroupID = priceGroupID;
	}
	public LinkedList getPiceGroupList() {
		return piceGroupList;
	}
	public void setPiceGroupList(LinkedList piceGroupList) {
		this.piceGroupList = piceGroupList;
	}
	public LinkedList getPriceListID() {
		return priceListID;
	}
	public void setPriceListID(LinkedList priceListID) {
		this.priceListID = priceListID;
	}
	public LinkedList getPiceListValue() {
		return piceListValue;
	}
	public void setPiceListValue(LinkedList piceListValue) {
		this.piceListValue = piceListValue;
	}
	public LinkedList getTaxTypeID() {
		return taxTypeID;
	}
	public void setTaxTypeID(LinkedList taxTypeID) {
		this.taxTypeID = taxTypeID;
	}
	public LinkedList getTaxTypeValue() {
		return taxTypeValue;
	}
	public void setTaxTypeValue(LinkedList taxTypeValue) {
		this.taxTypeValue = taxTypeValue;
	}
	public String getAccountView() {
		return accountView;
	}
	public void setAccountView(String accountView) {
		this.accountView = accountView;
	}
	public ArrayList getAccountGroupList() {
		return accountGroupList;
	}
	public void setAccountGroupList(ArrayList accountGroupList) {
		this.accountGroupList = accountGroupList;
	}
	public ArrayList getAccountGroupLabelList() {
		return accountGroupLabelList;
	}
	public void setAccountGroupLabelList(ArrayList accountGroupLabelList) {
		this.accountGroupLabelList = accountGroupLabelList;
	}
	public ArrayList getCountryList() {
		return countryList;
	}
	public void setCountryList(ArrayList countryList) {
		this.countryList = countryList;
	}
	public ArrayList getCountryLabelList() {
		return countryLabelList;
	}
	public void setCountryLabelList(ArrayList countryLabelList) {
		this.countryLabelList = countryLabelList;
	}
	public ArrayList getStateList() {
		return stateList;
	}
	public void setStateList(ArrayList stateList) {
		this.stateList = stateList;
	}
	public ArrayList getStateLabelList() {
		return stateLabelList;
	}
	public void setStateLabelList(ArrayList stateLabelList) {
		this.stateLabelList = stateLabelList;
	}
	public ArrayList getCurrencyList() {
		return currencyList;
	}
	public void setCurrencyList(ArrayList currencyList) {
		this.currencyList = currencyList;
	}
	public ArrayList getCurrencyLabelList() {
		return currencyLabelList;
	}
	public void setCurrencyLabelList(ArrayList currencyLabelList) {
		this.currencyLabelList = currencyLabelList;
	}
	public ArrayList getReConcillationList() {
		return reConcillationList;
	}
	public void setReConcillationList(ArrayList reConcillationList) {
		this.reConcillationList = reConcillationList;
	}
	public ArrayList getReConcillationLabelList() {
		return reConcillationLabelList;
	}
	public void setReConcillationLabelList(ArrayList reConcillationLabelList) {
		this.reConcillationLabelList = reConcillationLabelList;
	}
	public ArrayList getPaymentTermList() {
		return paymentTermList;
	}
	public void setPaymentTermList(ArrayList paymentTermList) {
		this.paymentTermList = paymentTermList;
	}
	public ArrayList getPaymentTermLabelList() {
		return paymentTermLabelList;
	}
	public void setPaymentTermLabelList(ArrayList paymentTermLabelList) {
		this.paymentTermLabelList = paymentTermLabelList;
	}
	public ArrayList getAccountClerkList() {
		return accountClerkList;
	}
	public void setAccountClerkList(ArrayList accountClerkList) {
		this.accountClerkList = accountClerkList;
	}
	public ArrayList getAccountClerkLabelList() {
		return accountClerkLabelList;
	}
	public void setAccountClerkLabelList(ArrayList accountClerkLabelList) {
		this.accountClerkLabelList = accountClerkLabelList;
	}
	public ArrayList getTdsIdList() {
		return tdsIdList;
	}
	public void setTdsIdList(ArrayList tdsIdList) {
		this.tdsIdList = tdsIdList;
	}
	public ArrayList getTdsLabelList() {
		return tdsLabelList;
	}
	public void setTdsLabelList(ArrayList tdsLabelList) {
		this.tdsLabelList = tdsLabelList;
	}
	public String getAccountGroupId() {
		return accountGroupId;
	}
	public void setAccountGroupId(String accountGroupId) {
		this.accountGroupId = accountGroupId;
	}
	public String getPurchaseView() {
		return purchaseView;
	}
	public void setPurchaseView(String purchaseView) {
		this.purchaseView = purchaseView;
	}
	public String getTitle() {
		return title;
	}
	public void setTitle(String title) {
		this.title = title;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public String getAddress1() {
		return address1;
	}
	public void setAddress1(String address1) {
		this.address1 = address1;
	}
	public String getAddress2() {
		return address2;
	}
	public void setAddress2(String address2) {
		this.address2 = address2;
	}
	public String getAddress3() {
		return address3;
	}
	public void setAddress3(String address3) {
		this.address3 = address3;
	}
	public String getAddress4() {
		return address4;
	}
	public void setAddress4(String address4) {
		this.address4 = address4;
	}
	public String getCity() {
		return city;
	}
	public void setCity(String city) {
		this.city = city;
	}
	public String getPinCode() {
		return pinCode;
	}
	public void setPinCode(String pinCode) {
		this.pinCode = pinCode;
	}
	public String getCountry() {
		return country;
	}
	public void setCountry(String country) {
		this.country = country;
	}
	public String getState() {
		return state;
	}
	public void setState(String state) {
		this.state = state;
	}
	public String getLandLineNo() {
		return landLineNo;
	}
	public void setLandLineNo(String landLineNo) {
		this.landLineNo = landLineNo;
	}
	public String getMobileNo() {
		return mobileNo;
	}
	public void setMobileNo(String mobileNo) {
		this.mobileNo = mobileNo;
	}
	public String getFaxNo() {
		return faxNo;
	}
	public void setFaxNo(String faxNo) {
		this.faxNo = faxNo;
	}
	public String getEmailId() {
		return emailId;
	}
	public void setEmailId(String emailId) {
		this.emailId = emailId;
	}
	public String getCurrencyId() {
		return currencyId;
	}
	public void setCurrencyId(String currencyId) {
		this.currencyId = currencyId;
	}
	public String getReConcillationActId() {
		return reConcillationActId;
	}
	public void setReConcillationActId(String reConcillationActId) {
		this.reConcillationActId = reConcillationActId;
	}
	public String getElgTds() {
		return elgTds;
	}
	public void setElgTds(String elgTds) {
		this.elgTds = elgTds;
	}
	public String getTdsCode() {
		return tdsCode;
	}
	public void setTdsCode(String tdsCode) {
		this.tdsCode = tdsCode;
	}
	public String getLstNo() {
		return lstNo;
	}
	public void setLstNo(String lstNo) {
		this.lstNo = lstNo;
	}
	public String getTinNo() {
		return tinNo;
	}
	public void setTinNo(String tinNo) {
		this.tinNo = tinNo;
	}
	public String getCstNo() {
		return cstNo;
	}
	public void setCstNo(String cstNo) {
		this.cstNo = cstNo;
	}
	public String getPanNo() {
		return panNo;
	}
	public void setPanNo(String panNo) {
		this.panNo = panNo;
	}
	public String getServiceTaxRegNo() {
		return serviceTaxRegNo;
	}
	public void setServiceTaxRegNo(String serviceTaxRegNo) {
		this.serviceTaxRegNo = serviceTaxRegNo;
	}
	public String getRegExciseVendor() {
		return regExciseVendor;
	}
	public void setRegExciseVendor(String regExciseVendor) {
		this.regExciseVendor = regExciseVendor;
	}
	public String getEccNo() {
		return eccNo;
	}
	public void setEccNo(String eccNo) {
		this.eccNo = eccNo;
	}
	public String getExciseRegNo() {
		return exciseRegNo;
	}
	public void setExciseRegNo(String exciseRegNo) {
		this.exciseRegNo = exciseRegNo;
	}
	public String getLinkName() {
		return linkName;
	}
	public void setLinkName(String linkName) {
		this.linkName = linkName;
	}
	public String getExciseRange() {
		return exciseRange;
	}
	public void setExciseRange(String exciseRange) {
		this.exciseRange = exciseRange;
	}
	public String getExciseDivision() {
		return exciseDivision;
	}
	public void setExciseDivision(String exciseDivision) {
		this.exciseDivision = exciseDivision;
	}
	public String getPaymentTermId() {
		return paymentTermId;
	}
	public void setPaymentTermId(String paymentTermId) {
		this.paymentTermId = paymentTermId;
	}
	public String getAccountClerkId() {
		return accountClerkId;
	}
	public void setAccountClerkId(String accountClerkId) {
		this.accountClerkId = accountClerkId;
	}
	public String getIsApprovedVendor() {
		return isApprovedVendor;
	}
	public void setIsApprovedVendor(String isApprovedVendor) {
		this.isApprovedVendor = isApprovedVendor;
	}
	public FormFile getVendorAttachments() {
		return vendorAttachments;
	}
	public void setVendorAttachments(FormFile vendorAttachments) {
		this.vendorAttachments = vendorAttachments;
	}
	public String getContentDescription() {
		return contentDescription;
	}
	public void setContentDescription(String contentDescription) {
		this.contentDescription = contentDescription;
	}
	public String getFileFullPath() {
		return fileFullPath;
	}
	public void setFileFullPath(String fileFullPath) {
		this.fileFullPath = fileFullPath;
	}
	public String getVideoFullPath() {
		return videoFullPath;
	}
	public void setVideoFullPath(String videoFullPath) {
		this.videoFullPath = videoFullPath;
	}
	public String getCommissionerate() {
		return commissionerate;
	}
	public void setCommissionerate(String commissionerate) {
		this.commissionerate = commissionerate;
	}
	public String getTypeOfVendor() {
		return typeOfVendor;
	}
	public void setTypeOfVendor(String typeOfVendor) {
		this.typeOfVendor = typeOfVendor;
	}
	public String getMoc() {
		return moc;
	}
	public void setMoc(String moc) {
		this.moc = moc;
	}
	public String getRating() {
		return rating;
	}
	public void setRating(String rating) {
		this.rating = rating;
	}
	public String getRange() {
		return range;
	}
	public void setRange(String range) {
		this.range = range;
	}
	public String getFromStorageLocation() {
		return fromStorageLocation;
	}
	public void setFromStorageLocation(String fromStorageLocation) {
		this.fromStorageLocation = fromStorageLocation;
	}
	public String getToStorageLocation() {
		return toStorageLocation;
	}
	public void setToStorageLocation(String toStorageLocation) {
		this.toStorageLocation = toStorageLocation;
	}
	public String getPlant2() {
		return plant2;
	}
	public void setPlant2(String plant2) {
		this.plant2 = plant2;
	}
	public String getMaterialCode2() {
		return materialCode2;
	}
	public void setMaterialCode2(String materialCode2) {
		this.materialCode2 = materialCode2;
	}
	public String getPlant1() {
		return plant1;
	}
	public void setPlant1(String plant1) {
		this.plant1 = plant1;
	}
	public String getMaterialCode1() {
		return materialCode1;
	}
	public void setMaterialCode1(String materialCode1) {
		this.materialCode1 = materialCode1;
	}
	public String getExtendToPlant1() {
		return extendToPlant1;
	}
	public void setExtendToPlant1(String extendToPlant1) {
		this.extendToPlant1 = extendToPlant1;
	}
	public String getStorageLocationId1() {
		return storageLocationId1;
	}
	public void setStorageLocationId1(String storageLocationId1) {
		this.storageLocationId1 = storageLocationId1;
	}
	public void setRequestNo(String requestNo) {
		this.requestNo = requestNo;
	}
	public LinkedList<Object> getUomId() {
		return uomId;
	}
	public void setUomId(LinkedList<Object> uomId) {
		this.uomId = uomId;
	}
	public LinkedList getUomLabel() {
		return uomLabel;
	}
	public void setUomLabel(LinkedList uomLabel) {
		this.uomLabel = uomLabel;
	}
	public LinkedList getPid() {
		return pid;
	}
	public void setPid(LinkedList pid) {
		this.pid = pid;
	}
	public LinkedList getPlabel() {
		return plabel;
	}
	public void setPlabel(LinkedList plabel) {
		this.plabel = plabel;
	}
	public LinkedList getVid() {
		return vid;
	}
	public void setVid(LinkedList vid) {
		this.vid = vid;
	}
	public LinkedList getVlabel() {
		return vlabel;
	}
	public void setVlabel(LinkedList vlabel) {
		this.vlabel = vlabel;
	}
	public LinkedList getPcode() {
		return pcode;
	}
	public void setPcode(LinkedList pcode) {
		this.pcode = pcode;
	}
	public LinkedList getSgroupLabel() {
		return sgroupLabel;
	}
	public void setSgroupLabel(LinkedList sgroupLabel) {
		this.sgroupLabel = sgroupLabel;
	}
	public LinkedList getServiceGroupID() {
		return serviceGroupID;
	}
	public void setServiceGroupID(LinkedList serviceGroupID) {
		this.serviceGroupID = serviceGroupID;
	}
	public LinkedList getServiceGroupValues() {
		return serviceGroupValues;
	}
	public void setServiceGroupValues(LinkedList serviceGroupValues) {
		this.serviceGroupValues = serviceGroupValues;
	}
	public String getMaterialtype() {
		return materialtype;
	}
	public void setMaterialtype(String materialtype) {
		this.materialtype = materialtype;
	}
	public String getMaterial_des() {
		return material_des;
	}
	public void setMaterial_des(String material_des) {
		this.material_des = material_des;
	}
	public String getMaterialGroup() {
		return materialGroup;
	}
	public void setMaterialGroup(String materialGroup) {
		this.materialGroup = materialGroup;
	}
	public String getMaterialPlant() {
		return materialPlant;
	}
	public void setMaterialPlant(String materialPlant) {
		this.materialPlant = materialPlant;
	}
	public String getLocationID() {
		return locationID;
	}
	public void setLocationID(String locationID) {
		this.locationID = locationID;
	}
	public String getServiceRequestDate() {
		return serviceRequestDate;
	}
	public void setServiceRequestDate(String serviceRequestDate) {
		this.serviceRequestDate = serviceRequestDate;
	}
	public String getServicePlant() {
		return servicePlant;
	}
	public void setServicePlant(String servicePlant) {
		this.servicePlant = servicePlant;
	}
	public String getServiceSatus() {
		return serviceSatus;
	}
	public void setServiceSatus(String serviceSatus) {
		this.serviceSatus = serviceSatus;
	}
	public String getServiceRequestedBy() {
		return serviceRequestedBy;
	}
	public void setServiceRequestedBy(String serviceRequestedBy) {
		this.serviceRequestedBy = serviceRequestedBy;
	}
	public String getServiceApproveDate() {
		return serviceApproveDate;
	}
	public void setServiceApproveDate(String serviceApproveDate) {
		this.serviceApproveDate = serviceApproveDate;
	}
	public String getCustomerRequestDate() {
		return customerRequestDate;
	}
	public void setCustomerRequestDate(String customerRequestDate) {
		this.customerRequestDate = customerRequestDate;
	}
	public String getCustomerLocation() {
		return customerLocation;
	}
	public void setCustomerLocation(String customerLocation) {
		this.customerLocation = customerLocation;
	}
	public String getC_country() {
		return c_country;
	}
	public void setC_country(String c_country) {
		this.c_country = c_country;
	}
	public String getC_customerGroup() {
		return c_customerGroup;
	}
	public void setC_customerGroup(String group) {
		c_customerGroup = group;
	}
	public String getC_status() {
		return c_status;
	}
	public void setC_status(String c_status) {
		this.c_status = c_status;
	}
	public int getR_no() {
		return r_no;
	}
	public void setR_no(int r_no) {
		this.r_no = r_no;
	}
	public String getPlantCode() {
		return plantCode;
	}
	public void setPlantCode(String plantCode) {
		this.plantCode = plantCode;
	}
	public String getStorageLocation() {
		return storageLocation;
	}
	public void setStorageLocation(String storageLocation) {
		this.storageLocation = storageLocation;
	}
	public String getServiceDescription() {
		return serviceDescription;
	}
	public void setServiceDescription(String serviceDescription) {
		this.serviceDescription = serviceDescription;
	}
	public String getDetailedServiceDescription() {
		return detailedServiceDescription;
	}
	public void setDetailedServiceDescription(String detailedServiceDescription) {
		this.detailedServiceDescription = detailedServiceDescription;
	}
	public String getUom() {
		return uom;
	}
	public void setUom(String uom) {
		this.uom = uom;
	}
	public String getPurchaseGroup() {
		return purchaseGroup;
	}
	public void setPurchaseGroup(String purchaseGroup) {
		this.purchaseGroup = purchaseGroup;
	}
	public String getServiceCatagory() {
		return serviceCatagory;
	}
	public void setServiceCatagory(String serviceCatagory) {
		this.serviceCatagory = serviceCatagory;
	}
	public String getServiceGroup() {
		return serviceGroup;
	}
	public void setServiceGroup(String serviceGroup) {
		this.serviceGroup = serviceGroup;
	}
	public String getE_m_name() {
		return e_m_name;
	}
	public void setE_m_name(String e_m_name) {
		this.e_m_name = e_m_name;
	}
	public String getApp_amount() {
		return app_amount;
	}
	public void setApp_amount(String app_amount) {
		this.app_amount = app_amount;
	}
	public String getWhereUsed() {
		return whereUsed;
	}
	public void setWhereUsed(String whereUsed) {
		this.whereUsed = whereUsed;
	}
	public String getPurpose() {
		return purpose;
	}
	public void setPurpose(String purpose) {
		this.purpose = purpose;
	}
	public String getJustification() {
		return justification;
	}
	public void setJustification(String justification) {
		this.justification = justification;
	}
	public FormFile getServiceAttachment() {
		return serviceAttachment;
	}
	public void setServiceAttachment(FormFile serviceAttachment) {
		this.serviceAttachment = serviceAttachment;
	}
	public String getApproveDate() {
		return approveDate;
	}
	public void setApproveDate(String approveDate) {
		this.approveDate = approveDate;
	}
	public String[] getDocumentCheck() {
		return documentCheck;
	}
	public void setDocumentCheck(String[] documentCheck) {
		this.documentCheck = documentCheck;
	}
	public String getFilepath() {
		return filepath;
	}
	public void setFilepath(String filepath) {
		this.filepath = filepath;
	}
	public String getU_id() {
		return u_id;
	}
	public void setU_id(String u_id) {
		this.u_id = u_id;
	}
	public String getU_label() {
		return u_label;
	}
	public void setU_label(String u_label) {
		this.u_label = u_label;
	}
	public String getP_id() {
		return p_id;
	}
	public void setP_id(String p_id) {
		this.p_id = p_id;
	}
	public String getP_all() {
		return p_all;
	}
	public void setP_all(String p_all) {
		this.p_all = p_all;
	}
	public String getPl_id() {
		return pl_id;
	}
	public void setPl_id(String pl_id) {
		this.pl_id = pl_id;
	}
	public String getPl_all() {
		return pl_all;
	}
	public void setPl_all(String pl_all) {
		this.pl_all = pl_all;
	}
	public String getService_id() {
		return service_id;
	}
	public void setService_id(String service_id) {
		this.service_id = service_id;
	}
	public String getService_label() {
		return service_label;
	}
	public void setService_label(String service_label) {
		this.service_label = service_label;
	}
	public String getSfile() {
		return sfile;
	}
	public void setSfile(String sfile) {
		this.sfile = sfile;
	}
	public String getIsSASFormAvailable() {
		return isSASFormAvailable;
	}
	public void setIsSASFormAvailable(String isSASFormAvailable) {
		this.isSASFormAvailable = isSASFormAvailable;
	}
	public String getIsAsset() {
		return isAsset;
	}
	public void setIsAsset(String isAsset) {
		this.isAsset = isAsset;
	}
	public String getMaterialUsedIn() {
		return materialUsedIn;
	}
	public void setMaterialUsedIn(String materialUsedIn) {
		this.materialUsedIn = materialUsedIn;
	}
	public String getIsEquipment() {
		return isEquipment;
	}
	public void setIsEquipment(String isEquipment) {
		this.isEquipment = isEquipment;
	}
	public String getIsSpare() {
		return isSpare;
	}
	public void setIsSpare(String isSpare) {
		this.isSpare = isSpare;
	}
	public String getIsNewEquipment() {
		return isNewEquipment;
	}
	public void setIsNewEquipment(String isNewEquipment) {
		this.isNewEquipment = isNewEquipment;
	}
	public String getIsItNewFurniture() {
		return isItNewFurniture;
	}
	public void setIsItNewFurniture(String isItNewFurniture) {
		this.isItNewFurniture = isItNewFurniture;
	}
	public String getIsItFacility() {
		return isItFacility;
	}
	public void setIsItFacility(String isItFacility) {
		this.isItFacility = isItFacility;
	}
	public String getIsSpareNewEquipment() {
		return isSpareNewEquipment;
	}
	public void setIsSpareNewEquipment(String isSpareNewEquipment) {
		this.isSpareNewEquipment = isSpareNewEquipment;
	}
	public String getEquipmentName() {
		return equipmentName;
	}
	public void setEquipmentName(String equipmentName) {
		this.equipmentName = equipmentName;
	}
	public String getPrNumber() {
		return prNumber;
	}
	public void setPrNumber(String prNumber) {
		this.prNumber = prNumber;
	}
	public String getPoNumber() {
		return poNumber;
	}
	public void setPoNumber(String poNumber) {
		this.poNumber = poNumber;
	}
	public String getUtilizingDept() {
		return utilizingDept;
	}
	public void setUtilizingDept(String utilizingDept) {
		this.utilizingDept = utilizingDept;
	}
	public String getDetailedJustification() {
		return detailedJustification;
	}
	public void setDetailedJustification(String detailedJustification) {
		this.detailedJustification = detailedJustification;
	}
	public String getDetailedSpecification() {
		return detailedSpecification;
	}
	public void setDetailedSpecification(String detailedSpecification) {
		this.detailedSpecification = detailedSpecification;
	}
	public String getPurposeID() {
		return purposeID;
	}
	public void setPurposeID(String purposeID) {
		this.purposeID = purposeID;
	}
	public LinkedList getDeptId() {
		return deptId;
	}
	public void setDeptId(LinkedList deptId) {
		this.deptId = deptId;
	}
	public LinkedList getDeptName() {
		return deptName;
	}
	public void setDeptName(LinkedList deptName) {
		this.deptName = deptName;
	}
	public String getEquipmentMake() {
		return equipmentMake;
	}
	public void setEquipmentMake(String equipmentMake) {
		this.equipmentMake = equipmentMake;
	}
	public String getComponentMake() {
		return componentMake;
	}
	public void setComponentMake(String componentMake) {
		this.componentMake = componentMake;
	}
	public String getOemPartNo() {
		return oemPartNo;
	}
	public void setOemPartNo(String oemPartNo) {
		this.oemPartNo = oemPartNo;
	}
	public String getPackSize() {
		return packSize;
	}
	public void setPackSize(String packSize) {
		this.packSize = packSize;
	}
	public String getTargetWeight() {
		return targetWeight;
	}
	public void setTargetWeight(String targetWeight) {
		this.targetWeight = targetWeight;
	}
	public String getPackageMaterialGroup() {
		return packageMaterialGroup;
	}
	public void setPackageMaterialGroup(String packageMaterialGroup) {
		this.packageMaterialGroup = packageMaterialGroup;
	}
	public String getTypeOfMaterial() {
		return typeOfMaterial;
	}
	public void setTypeOfMaterial(String typeOfMaterial) {
		this.typeOfMaterial = typeOfMaterial;
	}
	public String getArtworkNo() {
		return artworkNo;
	}
	public void setArtworkNo(String artworkNo) {
		this.artworkNo = artworkNo;
	}
	public String getIsArtworkRevision() {
		return isArtworkRevision;
	}
	public void setIsArtworkRevision(String isArtworkRevision) {
		this.isArtworkRevision = isArtworkRevision;
	}
	public String getExistingSAPItemCode() {
		return existingSAPItemCode;
	}
	public void setExistingSAPItemCode(String existingSAPItemCode) {
		this.existingSAPItemCode = existingSAPItemCode;
	}
	public LinkedList getPackageGroupID() {
		return packageGroupID;
	}
	public void setPackageGroupID(LinkedList packageGroupID) {
		this.packageGroupID = packageGroupID;
	}
	public LinkedList getPackageGroupIDValue() {
		return packageGroupIDValue;
	}
	public void setPackageGroupIDValue(LinkedList packageGroupIDValue) {
		this.packageGroupIDValue = packageGroupIDValue;
	}
	public String getManufacturedAt() {
		return manufacturedAt;
	}
	public void setManufacturedAt(String manufacturedAt) {
		this.manufacturedAt = manufacturedAt;
	}
	public String getShelfType() {
		return shelfType;
	}
	public void setShelfType(String shelfType) {
		this.shelfType = shelfType;
	}
	public String getStandardBatchSize() {
		return standardBatchSize;
	}
	public void setStandardBatchSize(String standardBatchSize) {
		this.standardBatchSize = standardBatchSize;
	}
	public String getBatchCode() {
		return batchCode;
	}
	public void setBatchCode(String batchCode) {
		this.batchCode = batchCode;
	}
	public String getSaleableOrSample() {
		return saleableOrSample;
	}
	public void setSaleableOrSample(String saleableOrSample) {
		this.saleableOrSample = saleableOrSample;
	}
	public String getDomesticOrExports() {
		return domesticOrExports;
	}
	public void setDomesticOrExports(String domesticOrExports) {
		this.domesticOrExports = domesticOrExports;
	}
	public String getSalesPackId() {
		return salesPackId;
	}
	public void setSalesPackId(String salesPackId) {
		this.salesPackId = salesPackId;
	}
	public String getPackTypeId() {
		return packTypeId;
	}
	public void setPackTypeId(String packTypeId) {
		this.packTypeId = packTypeId;
	}
	public String getTherapeuticSegmentID() {
		return therapeuticSegmentID;
	}
	public void setTherapeuticSegmentID(String therapeuticSegmentID) {
		this.therapeuticSegmentID = therapeuticSegmentID;
	}
	public String getDivisionId() {
		return divisionId;
	}
	public void setDivisionId(String divisionId) {
		this.divisionId = divisionId;
	}
	public String getBrandID() {
		return brandID;
	}
	public void setBrandID(String brandID) {
		this.brandID = brandID;
	}
	public String getSrengthId() {
		return srengthId;
	}
	public void setSrengthId(String srengthId) {
		this.srengthId = srengthId;
	}
	public String getProdInspMemo() {
		return prodInspMemo;
	}
	public void setProdInspMemo(String prodInspMemo) {
		this.prodInspMemo = prodInspMemo;
	}
	public String getGrossWeight() {
		return grossWeight;
	}
	public void setGrossWeight(String grossWeight) {
		this.grossWeight = grossWeight;
	}
	public String getNetWeight() {
		return netWeight;
	}
	public void setNetWeight(String netWeight) {
		this.netWeight = netWeight;
	}
	public String getWeightUOM() {
		return weightUOM;
	}
	public void setWeightUOM(String weightUOM) {
		this.weightUOM = weightUOM;
	}
	public String getDimension() {
		return dimension;
	}
	public void setDimension(String dimension) {
		this.dimension = dimension;
	}
	public String getSalesUnitOfMeaseurement() {
		return salesUnitOfMeaseurement;
	}
	public void setSalesUnitOfMeaseurement(String salesUnitOfMeaseurement) {
		this.salesUnitOfMeaseurement = salesUnitOfMeaseurement;
	}
	public String getTypeDetails() {
		return typeDetails;
	}
	public void setTypeDetails(String typeDetails) {
		this.typeDetails = typeDetails;
	}
	public LinkedList getPackSizeID() {
		return packSizeID;
	}
	public void setPackSizeID(LinkedList packSizeID) {
		this.packSizeID = packSizeID;
	}
	public LinkedList getPackSizeName() {
		return packSizeName;
	}
	public void setPackSizeName(LinkedList packSizeName) {
		this.packSizeName = packSizeName;
	}
	public LinkedList getPackTypeID() {
		return packTypeID;
	}
	public void setPackTypeID(LinkedList packTypeID) {
		this.packTypeID = packTypeID;
	}
	public LinkedList getPackTypeName() {
		return packTypeName;
	}
	public void setPackTypeName(LinkedList packTypeName) {
		this.packTypeName = packTypeName;
	}
	public LinkedList getSalesUOMID() {
		return salesUOMID;
	}
	public void setSalesUOMID(LinkedList salesUOMID) {
		this.salesUOMID = salesUOMID;
	}
	public LinkedList getSalesUOMName() {
		return salesUOMName;
	}
	public void setSalesUOMName(LinkedList salesUOMName) {
		this.salesUOMName = salesUOMName;
	}
	public LinkedList getDivisonID() {
		return divisonID;
	}
	public void setDivisonID(LinkedList divisonID) {
		this.divisonID = divisonID;
	}
	public LinkedList getDivisonName() {
		return divisonName;
	}
	public void setDivisonName(LinkedList divisonName) {
		this.divisonName = divisonName;
	}
	public LinkedList getTherapeuticID() {
		return therapeuticID;
	}
	public void setTherapeuticID(LinkedList therapeuticID) {
		this.therapeuticID = therapeuticID;
	}
	public LinkedList getTherapeuticName() {
		return therapeuticName;
	}
	public void setTherapeuticName(LinkedList therapeuticName) {
		this.therapeuticName = therapeuticName;
	}
	public LinkedList getBrandIDList() {
		return brandIDList;
	}
	public void setBrandIDList(LinkedList brandIDList) {
		this.brandIDList = brandIDList;
	}
	public LinkedList getBrandNameList() {
		return brandNameList;
	}
	public void setBrandNameList(LinkedList brandNameList) {
		this.brandNameList = brandNameList;
	}
	public LinkedList getStrengthIDList() {
		return strengthIDList;
	}
	public void setStrengthIDList(LinkedList strengthIDList) {
		this.strengthIDList = strengthIDList;
	}
	public LinkedList getStrengthNameList() {
		return strengthNameList;
	}
	public void setStrengthNameList(LinkedList strengthNameList) {
		this.strengthNameList = strengthNameList;
	}
	public LinkedList getGenericIDList() {
		return genericIDList;
	}
	public void setGenericIDList(LinkedList genericIDList) {
		this.genericIDList = genericIDList;
	}
	public LinkedList getGenericNameList() {
		return genericNameList;
	}
	public void setGenericNameList(LinkedList genericNameList) {
		this.genericNameList = genericNameList;
	}
	public LinkedList getWeightUOMID() {
		return weightUOMID;
	}
	public void setWeightUOMID(LinkedList weightUOMID) {
		this.weightUOMID = weightUOMID;
	}
	public LinkedList getWeightUOMName() {
		return weightUOMName;
	}
	public void setWeightUOMName(LinkedList weightUOMName) {
		this.weightUOMName = weightUOMName;
	}
	public String getTaxClassification() {
		return taxClassification;
	}
	public void setTaxClassification(String taxClassification) {
		this.taxClassification = taxClassification;
	}
	public String getMaterialPricing() {
		return materialPricing;
	}
	public void setMaterialPricing(String materialPricing) {
		this.materialPricing = materialPricing;
	}
	public String getSapCodeExistsNo() {
		return sapCodeExistsNo;
	}
	public void setSapCodeExistsNo(String sapCodeExistsNo) {
		this.sapCodeExistsNo = sapCodeExistsNo;
	}
	public String getReqMaterialGroup() {
		return reqMaterialGroup;
	}
	public void setReqMaterialGroup(String reqMaterialGroup) {
		this.reqMaterialGroup = reqMaterialGroup;
	}
	public String getEmployeeCode() {
		return employeeCode;
	}
	public void setEmployeeCode(String employeeCode) {
		this.employeeCode = employeeCode;
	}


	public String getEmployeeName() {
		return employeeName;
	}
	public void setEmployeeName(String employeeName) {
		this.employeeName = employeeName;
	}
	public String getApproveStatus() {
		return approveStatus;
	}
	public void setApproveStatus(String approveStatus) {
		this.approveStatus = approveStatus;
	}
	public String getDate() {
		return date;
	}
	public void setDate(String date) {
		this.date = date;
	}
	public String getPriority() {
		return priority;
	}
	public void setPriority(String priority) {
		this.priority = priority;
	}
	public String getUserRole() {
		return userRole;
	}
	public void setUserRole(String userRole) {
		this.userRole = userRole;
	}
	public String getComments() {
		return comments;
	}
	public void setComments(String comments) {
		this.comments = comments;
	}
	public String getLocationId() {
		return locationId;
	}
	public void setLocationId(String locationId) {
		this.locationId = locationId;
	}
	public String getStorageLocationId() {
		return storageLocationId;
	}
	public void setStorageLocationId(String storageLocationId) {
		this.storageLocationId = storageLocationId;
	}
	public String getMaterialTypeId() {
		return materialTypeId;
	}
	public void setMaterialTypeId(String materialTypeId) {
		this.materialTypeId = materialTypeId;
	}
	public String getMaterialShortName() {
		return materialShortName;
	}
	public void setMaterialShortName(String materialShortName) {
		this.materialShortName = materialShortName;
	}
	public String getMaterialLongName() {
		return materialLongName;
	}
	public void setMaterialLongName(String materialLongName) {
		this.materialLongName = materialLongName;
	}
	public String getMaterialGroupId() {
		return materialGroupId;
	}
	public void setMaterialGroupId(String materialGroupId) {
		this.materialGroupId = materialGroupId;
	}
	public String getPharmacopName() {
		return pharmacopName;
	}
	public void setPharmacopName(String pharmacopName) {
		this.pharmacopName = pharmacopName;
	}
	public String getPharmacopGrade() {
		return pharmacopGrade;
	}
	public void setPharmacopGrade(String pharmacopGrade) {
		this.pharmacopGrade = pharmacopGrade;
	}
	public String getGenericName() {
		return genericName;
	}
	public void setGenericName(String genericName) {
		this.genericName = genericName;
	}
	public String getSynonym() {
		return synonym;
	}
	public void setSynonym(String synonym) {
		this.synonym = synonym;
	}
	public String getPharmacopSpecification() {
		return pharmacopSpecification;
	}
	public void setPharmacopSpecification(String pharmacopSpecification) {
		this.pharmacopSpecification = pharmacopSpecification;
	}
	public String getIsDMFMaterial() {
		return isDMFMaterial;
	}
	public void setIsDMFMaterial(String isDMFMaterial) {
		this.isDMFMaterial = isDMFMaterial;
	}
	public String getShelfLifeType() {
		return shelfLifeType;
	}
	public void setShelfLifeType(String shelfLifeType) {
		this.shelfLifeType = shelfLifeType;
	}
	public String getRetestType() {
		return retestType;
	}
	public void setRetestType(String retestType) {
		this.retestType = retestType;
	}
	public String getDmfGradeId() {
		return dmfGradeId;
	}
	public void setDmfGradeId(String dmfGradeId) {
		this.dmfGradeId = dmfGradeId;
	}
	public String getMaterialGrade() {
		return materialGrade;
	}
	public void setMaterialGrade(String materialGrade) {
		this.materialGrade = materialGrade;
	}
	public String getCosGradeNo() {
		return cosGradeNo;
	}
	public void setCosGradeNo(String cosGradeNo) {
		this.cosGradeNo = cosGradeNo;
	}
	public String getAdditionalTest() {
		return additionalTest;
	}
	public void setAdditionalTest(String additionalTest) {
		this.additionalTest = additionalTest;
	}
	public String getCountryId() {
		return countryId;
	}
	public void setCountryId(String countryId) {
		this.countryId = countryId;
	}
	public String getCustomerName() {
		return customerName;
	}
	public void setCustomerName(String customerName) {
		this.customerName = customerName;
	}
	public String getToBeUsedInProducts() {
		return toBeUsedInProducts;
	}
	public void setToBeUsedInProducts(String toBeUsedInProducts) {
		this.toBeUsedInProducts = toBeUsedInProducts;
	}
	public String getIsVendorSpecificMaterial() {
		return isVendorSpecificMaterial;
	}
	public void setIsVendorSpecificMaterial(String isVendorSpecificMaterial) {
		this.isVendorSpecificMaterial = isVendorSpecificMaterial;
	}
	public String getMfgrName() {
		return mfgrName;
	}
	public void setMfgrName(String mfgrName) {
		this.mfgrName = mfgrName;
	}
	public String getSiteOfManufacture() {
		return siteOfManufacture;
	}
	public void setSiteOfManufacture(String siteOfManufacture) {
		this.siteOfManufacture = siteOfManufacture;
	}
	public String getTempCondition() {
		return tempCondition;
	}
	public void setTempCondition(String tempCondition) {
		this.tempCondition = tempCondition;
	}
	public String getStorageCondition() {
		return storageCondition;
	}
	public void setStorageCondition(String storageCondition) {
		this.storageCondition = storageCondition;
	}
	public String getShelfLife() {
		return shelfLife;
	}
	public void setShelfLife(String shelfLife) {
		this.shelfLife = shelfLife;
	}
	public String getDutyElement() {
		return dutyElement;
	}
	public void setDutyElement(String dutyElement) {
		this.dutyElement = dutyElement;
	}
	public String getRetestDays() {
		return retestDays;
	}
	public void setRetestDays(String retestDays) {
		this.retestDays = retestDays;
	}
	public String getValuationClass() {
		return valuationClass;
	}
	public void setValuationClass(String valuationClass) {
		this.valuationClass = valuationClass;
	}
	public String getApproximateValue() {
		return approximateValue;
	}
	public void setApproximateValue(String approximateValue) {
		this.approximateValue = approximateValue;
	}
	public String getUnitOfMeasId() {
		return unitOfMeasId;
	}
	public void setUnitOfMeasId(String unitOfMeasId) {
		this.unitOfMeasId = unitOfMeasId;
	}
	public String getPuchaseGroupId() {
		return puchaseGroupId;
	}
	public void setPuchaseGroupId(String puchaseGroupId) {
		this.puchaseGroupId = puchaseGroupId;
	}
	public String getMessage2() {
		return message2;
	}
	public void setMessage2(String message2) {
		this.message2 = message2;
	}
	public String getRequestNumber() {
		return requestNumber;
	}
	public void setRequestNumber(String requestNumber) {
		this.requestNumber = requestNumber;
	}
	public String getRequestsearchDate() {
		return requestsearchDate;
	}
	public void setRequestsearchDate(String requestsearchDate) {
		this.requestsearchDate = requestsearchDate;
	}
	public String getLocationSearch() {
		return locationSearch;
	}
	public void setLocationSearch(String locationSearch) {
		this.locationSearch = locationSearch;
	}
	public FormFile getFileNames() {
		return fileNames;
	}
	public void setFileNames(FormFile fileNames) {
		this.fileNames = fileNames;
	}
	public String getFileList() {
		return fileList;
	}
	public void setFileList(String fileList) {
		this.fileList = fileList;
	}
	public String getMaterialCodeLists() {
		return materialCodeLists;
	}
	public void setMaterialCodeLists(String materialCodeLists) {
		this.materialCodeLists = materialCodeLists;
	}
	public String getMaterialCodeLists1() {
		return materialCodeLists1;
	}
	public void setMaterialCodeLists1(String materialCodeLists1) {
		this.materialCodeLists1 = materialCodeLists1;
	}
	public String getApproveType() {
		return approveType;
	}
	public void setApproveType(String approveType) {
		this.approveType = approveType;
	}
	public String getRequiredRequestNumber() {
		return requiredRequestNumber;
	}
	public void setRequiredRequestNumber(String requiredRequestNumber) {
		this.requiredRequestNumber = requiredRequestNumber;
	}
	public ArrayList getLocationIdList() {
		return locationIdList;
	}
	public void setLocationIdList(ArrayList locationIdList) {
		this.locationIdList = locationIdList;
	}
	public ArrayList getLocationLabelList() {
		return locationLabelList;
	}
	public void setLocationLabelList(ArrayList locationLabelList) {
		this.locationLabelList = locationLabelList;
	}
	public LinkedList getStorageID() {
		return storageID;
	}
	public void setStorageID(LinkedList storageID) {
		this.storageID = storageID;
	}
	public LinkedList getStorageIDName() {
		return storageIDName;
	}
	public void setStorageIDName(LinkedList storageIDName) {
		this.storageIDName = storageIDName;
	}
	public LinkedList getMaterTypeIDList() {
		return materTypeIDList;
	}
	public void setMaterTypeIDList(LinkedList materTypeIDList) {
		this.materTypeIDList = materTypeIDList;
	}
	public LinkedList getMaterialTypeIdValueList() {
		return materialTypeIdValueList;
	}
	public void setMaterialTypeIdValueList(LinkedList materialTypeIdValueList) {
		this.materialTypeIdValueList = materialTypeIdValueList;
	}
	public LinkedList getMaterGroupIDList() {
		return materGroupIDList;
	}
	public void setMaterGroupIDList(LinkedList materGroupIDList) {
		this.materGroupIDList = materGroupIDList;
	}
	public LinkedList getMaterialGroupIdValueList() {
		return materialGroupIdValueList;
	}
	public void setMaterialGroupIdValueList(LinkedList materialGroupIdValueList) {
		this.materialGroupIdValueList = materialGroupIdValueList;
	}
	public LinkedList getUnitOfMeasIdList() {
		return unitOfMeasIdList;
	}
	public void setUnitOfMeasIdList(LinkedList unitOfMeasIdList) {
		this.unitOfMeasIdList = unitOfMeasIdList;
	}
	public LinkedList getUnitOfMeasIdValues() {
		return unitOfMeasIdValues;
	}
	public void setUnitOfMeasIdValues(LinkedList unitOfMeasIdValues) {
		this.unitOfMeasIdValues = unitOfMeasIdValues;
	}
	public LinkedList getPharmacopGradeIDList() {
		return pharmacopGradeIDList;
	}
	public void setPharmacopGradeIDList(LinkedList pharmacopGradeIDList) {
		this.pharmacopGradeIDList = pharmacopGradeIDList;
	}
	public LinkedList getPharmacopGradeValueList() {
		return pharmacopGradeValueList;
	}
	public void setPharmacopGradeValueList(LinkedList pharmacopGradeValueList) {
		this.pharmacopGradeValueList = pharmacopGradeValueList;
	}
	public LinkedList getValuationClassID() {
		return valuationClassID;
	}
	public void setValuationClassID(LinkedList valuationClassID) {
		this.valuationClassID = valuationClassID;
	}
	public LinkedList getValuationClassName() {
		return valuationClassName;
	}
	public void setValuationClassName(LinkedList valuationClassName) {
		this.valuationClassName = valuationClassName;
	}
	public LinkedList getDmfGradeIDList() {
		return dmfGradeIDList;
	}
	public void setDmfGradeIDList(LinkedList dmfGradeIDList) {
		this.dmfGradeIDList = dmfGradeIDList;
	}
	public LinkedList getDmfGradeIDValueList() {
		return dmfGradeIDValueList;
	}
	public void setDmfGradeIDValueList(LinkedList dmfGradeIDValueList) {
		this.dmfGradeIDValueList = dmfGradeIDValueList;
	}
	public LinkedList getCounID() {
		return counID;
	}
	public void setCounID(LinkedList counID) {
		this.counID = counID;
	}
	public LinkedList getCountryName() {
		return countryName;
	}
	public void setCountryName(LinkedList countryName) {
		this.countryName = countryName;
	}
	public LinkedList getPuchaseGroupIdList() {
		return puchaseGroupIdList;
	}
	public void setPuchaseGroupIdList(LinkedList puchaseGroupIdList) {
		this.puchaseGroupIdList = puchaseGroupIdList;
	}
	public LinkedList getPuchaseGroupIdValues() {
		return puchaseGroupIdValues;
	}
	public void setPuchaseGroupIdValues(LinkedList puchaseGroupIdValues) {
		this.puchaseGroupIdValues = puchaseGroupIdValues;
	}
	public LinkedList getSapCodeNoIdList() {
		return sapCodeNoIdList;
	}
	public void setSapCodeNoIdList(LinkedList sapCodeNoIdList) {
		this.sapCodeNoIdList = sapCodeNoIdList;
	}
	public LinkedList getSapCodeNoIdValues() {
		return sapCodeNoIdValues;
	}
	public void setSapCodeNoIdValues(LinkedList sapCodeNoIdValues) {
		this.sapCodeNoIdValues = sapCodeNoIdValues;
	}
	public LinkedList getTempIDList() {
		return tempIDList;
	}
	public void setTempIDList(LinkedList tempIDList) {
		this.tempIDList = tempIDList;
	}
	public LinkedList getTemValueList() {
		return temValueList;
	}
	public void setTemValueList(LinkedList temValueList) {
		this.temValueList = temValueList;
	}
	public LinkedList getStorageIDList() {
		return storageIDList;
	}
	public void setStorageIDList(LinkedList storageIDList) {
		this.storageIDList = storageIDList;
	}
	public LinkedList getStorageLocList() {
		return storageLocList;
	}
	public void setStorageLocList(LinkedList storageLocList) {
		this.storageLocList = storageLocList;
	}
	public String getMessage() {
		return message;
	}
	public void setMessage(String message) {
		this.message = message;
	}
	public String[] getSelectedRequestNo() {
		return selectedRequestNo;
	}
	public void setSelectedRequestNo(String[] selectedRequestNo) {
		this.selectedRequestNo = selectedRequestNo;
	}
	public int getTotalRecords() {
		return totalRecords;
	}
	public void setTotalRecords(int totalRecords) {
		this.totalRecords = totalRecords;
	}
	public int getStartRecord() {
		return startRecord;
	}
	public void setStartRecord(int startRecord) {
		this.startRecord = startRecord;
	}
	public int getEndRecord() {
		return endRecord;
	}
	public void setEndRecord(int endRecord) {
		this.endRecord = endRecord;
	}
	public String getRequestNo() {
		return requestNo;
	}
	public void RequestNo(String requestNo) {
		this.requestNo = requestNo;
	}
	public String getRequestDate() {
		return requestDate;
	}
	public void setRequestDate(String requestDate) {
		this.requestDate = requestDate;
	}
	public String getRequestType() {
		return requestType;
	}
	public void setRequestType(String requestType) {
		this.requestType = requestType;
	}
	public String getRequestedBy() {
		return requestedBy;
	}
	public void setRequestedBy(String requestedBy) {
		this.requestedBy = requestedBy;
	}
	
	public String getHeader() {
		return header;
	}
	public void setHeader(String header) {
		this.header = header;
	}
	
	public String getJobTitle() {
		return jobTitle;
	}
	public void setJobTitle(String jobTitle) {
		this.jobTitle = jobTitle;
	}
	public String getDepartment() {
		return department;
	}
	public void setDepartment(String department) {
		this.department = department;
	}
	public String getPrimaryLocation() {
		return primaryLocation;
	}
	public void setPrimaryLocation(String primaryLocation) {
		this.primaryLocation = primaryLocation;
	}
	
	public String getRemark() {
		return remark;
	}
	public void setRemark(String rmark) {
		this.remark = rmark;
	}
	
	public String getJobDescription() {
		return jobDescription;
	}
	public void setJobDescription(String jobDescription) {
		this.jobDescription = jobDescription;
	}
	
	public String getEmpStatus() {
		return empStatus;
	}
	public void setEmpStatus(String empStatus) {
		this.empStatus = empStatus;
	}
	
	public String getTotalEmp() {
		return totalEmp;
	}
	public void setTotalEmp(String totalEmp) {
		this.totalEmp = totalEmp;
	}
	
	public String getQualifications() {
		return qualifications;
	}
	public void setQualifications(String qualifications) {
		this.qualifications = qualifications;
	}
	public String getExperience() {
		return experience;
	}
	public void setExperience(String experience) {
		this.experience = experience;
	}
	public String getSaleryOffered() {
		return saleryOffered;
	}
	public void setSaleryOffered(String saleryOffered) {
		this.saleryOffered = saleryOffered;
	}
	public String getUrl() {
		return url;
	}
	public void setUrl(String url) {
		this.url = url;
	}
	public String getReqStatus() {
		return reqStatus;
	}
	public void setReqStatus(String reqStatus) {
		this.reqStatus = reqStatus;
	}
	public String getAppMessage() {
		return appMessage;
	}
	public void setAppMessage(String appMessage) {
		this.appMessage = appMessage;
	}
	public int getStartAppCount() {
		return startAppCount;
	}
	public void setStartAppCount(int startAppCount) {
		this.startAppCount = startAppCount;
	}
	
	
	public int getEndAppCount() {
		return endAppCount;
	}
	public void setEndAppCount(int endAppCount) {
		this.endAppCount = endAppCount;
	}
	
	
	public int getTotalAppCount() {
		return totalAppCount;
	}
	public void setTotalAppCount(int totalAppCount) {
		this.totalAppCount = totalAppCount;
	}
	public LinkedList getFilterType() {
		return filterType;
	}
	public void setFilterType(LinkedList fType) {
		this.filterType = fType;
	}
	public String getSelectedFilter() {
		return selectedFilter;
	}
	public void setSelectedFilter(String selectedFilter) {
		this.selectedFilter = selectedFilter;
	}
	
	public String getFileNameList() {
		return fileNameList;
	}
	public void setFileNameList(String fileList) {
		this.fileNameList = fileList;
	}
	
	public String getReqRequstType() {
		return reqRequstType;
	}
	public void setReqRequstType(String reqRequstType) {
		this.reqRequstType = reqRequstType;
	}
	
	public String getSapCodeNo() {
		return sapCodeNo;
	}
	public void setSapCodeNo(String sapCodeNo) {
		this.sapCodeNo = sapCodeNo;
	}
	public String getSapCodeExists() {
		return sapCodeExists;
	}
	public void setSapCodeExists(String sapCodeExists) {
		this.sapCodeExists = sapCodeExists;
	}
	public String getSapCreationDate() {
		return sapCreationDate;
	}
	public void setSapCreationDate(String sapCreationDate) {
		this.sapCreationDate = sapCreationDate;
	}
	public String getSapCreatedBy() {
		return sapCreatedBy;
	}
	public void setSapCreatedBy(String sapCreatedBy) {
		this.sapCreatedBy = sapCreatedBy;
	}
	public String getHeading(){
		return heading;
	}
	public void setHeading(String heading) {
		this.heading = heading;
	}
	
	public String getSearchText(){
		return searchText;
	}
	public void setSearchText(String searchText) {
		this.searchText = searchText;
	}
	
	public String getMethod() {
		return method;
	}
	public void setMethod(String method) {
		this.method = method;
	}
	public String getPlantType() {
		return plantType;
	}
	public void setPlantType(String plantType) {
		this.plantType = plantType;
	}
	public String getExtendToStorageLocation1() {
		return extendToStorageLocation1;
	}
	public void setExtendToStorageLocation1(String extendToStorageLocation1) {
		this.extendToStorageLocation1 = extendToStorageLocation1;
	}
}